
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Eventos_Integrantes` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Eventos_Integrantes
 * 
 */
export type Eventos_IntegrantesModel = runtime.Types.Result.DefaultSelection<Prisma.$Eventos_IntegrantesPayload>

export type AggregateEventos_Integrantes = {
  _count: Eventos_IntegrantesCountAggregateOutputType | null
  _min: Eventos_IntegrantesMinAggregateOutputType | null
  _max: Eventos_IntegrantesMaxAggregateOutputType | null
}

export type Eventos_IntegrantesMinAggregateOutputType = {
  id: string | null
  evento_id: string | null
  musico_id: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Eventos_IntegrantesMaxAggregateOutputType = {
  id: string | null
  evento_id: string | null
  musico_id: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Eventos_IntegrantesCountAggregateOutputType = {
  id: number
  evento_id: number
  musico_id: number
  created_at: number
  updated_at: number
  _all: number
}


export type Eventos_IntegrantesMinAggregateInputType = {
  id?: true
  evento_id?: true
  musico_id?: true
  created_at?: true
  updated_at?: true
}

export type Eventos_IntegrantesMaxAggregateInputType = {
  id?: true
  evento_id?: true
  musico_id?: true
  created_at?: true
  updated_at?: true
}

export type Eventos_IntegrantesCountAggregateInputType = {
  id?: true
  evento_id?: true
  musico_id?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Eventos_IntegrantesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Eventos_Integrantes to aggregate.
   */
  where?: Prisma.Eventos_IntegrantesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Eventos_Integrantes to fetch.
   */
  orderBy?: Prisma.Eventos_IntegrantesOrderByWithRelationInput | Prisma.Eventos_IntegrantesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.Eventos_IntegrantesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Eventos_Integrantes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Eventos_Integrantes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Eventos_Integrantes
  **/
  _count?: true | Eventos_IntegrantesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Eventos_IntegrantesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Eventos_IntegrantesMaxAggregateInputType
}

export type GetEventos_IntegrantesAggregateType<T extends Eventos_IntegrantesAggregateArgs> = {
      [P in keyof T & keyof AggregateEventos_Integrantes]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventos_Integrantes[P]>
    : Prisma.GetScalarType<T[P], AggregateEventos_Integrantes[P]>
}




export type Eventos_IntegrantesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Eventos_IntegrantesWhereInput
  orderBy?: Prisma.Eventos_IntegrantesOrderByWithAggregationInput | Prisma.Eventos_IntegrantesOrderByWithAggregationInput[]
  by: Prisma.Eventos_IntegrantesScalarFieldEnum[] | Prisma.Eventos_IntegrantesScalarFieldEnum
  having?: Prisma.Eventos_IntegrantesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Eventos_IntegrantesCountAggregateInputType | true
  _min?: Eventos_IntegrantesMinAggregateInputType
  _max?: Eventos_IntegrantesMaxAggregateInputType
}

export type Eventos_IntegrantesGroupByOutputType = {
  id: string
  evento_id: string
  musico_id: string
  created_at: Date
  updated_at: Date
  _count: Eventos_IntegrantesCountAggregateOutputType | null
  _min: Eventos_IntegrantesMinAggregateOutputType | null
  _max: Eventos_IntegrantesMaxAggregateOutputType | null
}

type GetEventos_IntegrantesGroupByPayload<T extends Eventos_IntegrantesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Eventos_IntegrantesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Eventos_IntegrantesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Eventos_IntegrantesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Eventos_IntegrantesGroupByOutputType[P]>
      }
    >
  >



export type Eventos_IntegrantesWhereInput = {
  AND?: Prisma.Eventos_IntegrantesWhereInput | Prisma.Eventos_IntegrantesWhereInput[]
  OR?: Prisma.Eventos_IntegrantesWhereInput[]
  NOT?: Prisma.Eventos_IntegrantesWhereInput | Prisma.Eventos_IntegrantesWhereInput[]
  id?: Prisma.UuidFilter<"Eventos_Integrantes"> | string
  evento_id?: Prisma.UuidFilter<"Eventos_Integrantes"> | string
  musico_id?: Prisma.UuidFilter<"Eventos_Integrantes"> | string
  created_at?: Prisma.DateTimeFilter<"Eventos_Integrantes"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Eventos_Integrantes"> | Date | string
  eventos_integrantes_evento_id_fkey?: Prisma.XOR<Prisma.EventosScalarRelationFilter, Prisma.EventosWhereInput>
  eventos_integrantes_musico_id_fkey?: Prisma.XOR<Prisma.IntegrantesScalarRelationFilter, Prisma.IntegrantesWhereInput>
}

export type Eventos_IntegrantesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  evento_id?: Prisma.SortOrder
  musico_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  eventos_integrantes_evento_id_fkey?: Prisma.EventosOrderByWithRelationInput
  eventos_integrantes_musico_id_fkey?: Prisma.IntegrantesOrderByWithRelationInput
}

export type Eventos_IntegrantesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.Eventos_IntegrantesWhereInput | Prisma.Eventos_IntegrantesWhereInput[]
  OR?: Prisma.Eventos_IntegrantesWhereInput[]
  NOT?: Prisma.Eventos_IntegrantesWhereInput | Prisma.Eventos_IntegrantesWhereInput[]
  evento_id?: Prisma.UuidFilter<"Eventos_Integrantes"> | string
  musico_id?: Prisma.UuidFilter<"Eventos_Integrantes"> | string
  created_at?: Prisma.DateTimeFilter<"Eventos_Integrantes"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Eventos_Integrantes"> | Date | string
  eventos_integrantes_evento_id_fkey?: Prisma.XOR<Prisma.EventosScalarRelationFilter, Prisma.EventosWhereInput>
  eventos_integrantes_musico_id_fkey?: Prisma.XOR<Prisma.IntegrantesScalarRelationFilter, Prisma.IntegrantesWhereInput>
}, "id">

export type Eventos_IntegrantesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  evento_id?: Prisma.SortOrder
  musico_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.Eventos_IntegrantesCountOrderByAggregateInput
  _max?: Prisma.Eventos_IntegrantesMaxOrderByAggregateInput
  _min?: Prisma.Eventos_IntegrantesMinOrderByAggregateInput
}

export type Eventos_IntegrantesScalarWhereWithAggregatesInput = {
  AND?: Prisma.Eventos_IntegrantesScalarWhereWithAggregatesInput | Prisma.Eventos_IntegrantesScalarWhereWithAggregatesInput[]
  OR?: Prisma.Eventos_IntegrantesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.Eventos_IntegrantesScalarWhereWithAggregatesInput | Prisma.Eventos_IntegrantesScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Eventos_Integrantes"> | string
  evento_id?: Prisma.UuidWithAggregatesFilter<"Eventos_Integrantes"> | string
  musico_id?: Prisma.UuidWithAggregatesFilter<"Eventos_Integrantes"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Eventos_Integrantes"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Eventos_Integrantes"> | Date | string
}

export type Eventos_IntegrantesCreateInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  eventos_integrantes_evento_id_fkey: Prisma.EventosCreateNestedOneWithoutEventos_IntegrantesInput
  eventos_integrantes_musico_id_fkey: Prisma.IntegrantesCreateNestedOneWithoutEventos_IntegrantesInput
}

export type Eventos_IntegrantesUncheckedCreateInput = {
  id?: string
  evento_id: string
  musico_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Eventos_IntegrantesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventos_integrantes_evento_id_fkey?: Prisma.EventosUpdateOneRequiredWithoutEventos_IntegrantesNestedInput
  eventos_integrantes_musico_id_fkey?: Prisma.IntegrantesUpdateOneRequiredWithoutEventos_IntegrantesNestedInput
}

export type Eventos_IntegrantesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  evento_id?: Prisma.StringFieldUpdateOperationsInput | string
  musico_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Eventos_IntegrantesCreateManyInput = {
  id?: string
  evento_id: string
  musico_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Eventos_IntegrantesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Eventos_IntegrantesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  evento_id?: Prisma.StringFieldUpdateOperationsInput | string
  musico_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Eventos_IntegrantesListRelationFilter = {
  every?: Prisma.Eventos_IntegrantesWhereInput
  some?: Prisma.Eventos_IntegrantesWhereInput
  none?: Prisma.Eventos_IntegrantesWhereInput
}

export type Eventos_IntegrantesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Eventos_IntegrantesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  evento_id?: Prisma.SortOrder
  musico_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type Eventos_IntegrantesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  evento_id?: Prisma.SortOrder
  musico_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type Eventos_IntegrantesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  evento_id?: Prisma.SortOrder
  musico_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type Eventos_IntegrantesCreateNestedManyWithoutEventos_integrantes_evento_id_fkeyInput = {
  create?: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_evento_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_evento_id_fkeyInput> | Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_evento_id_fkeyInput[] | Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_evento_id_fkeyInput[]
  connectOrCreate?: Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_evento_id_fkeyInput | Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_evento_id_fkeyInput[]
  createMany?: Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_evento_id_fkeyInputEnvelope
  connect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
}

export type Eventos_IntegrantesUncheckedCreateNestedManyWithoutEventos_integrantes_evento_id_fkeyInput = {
  create?: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_evento_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_evento_id_fkeyInput> | Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_evento_id_fkeyInput[] | Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_evento_id_fkeyInput[]
  connectOrCreate?: Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_evento_id_fkeyInput | Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_evento_id_fkeyInput[]
  createMany?: Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_evento_id_fkeyInputEnvelope
  connect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
}

export type Eventos_IntegrantesUpdateManyWithoutEventos_integrantes_evento_id_fkeyNestedInput = {
  create?: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_evento_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_evento_id_fkeyInput> | Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_evento_id_fkeyInput[] | Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_evento_id_fkeyInput[]
  connectOrCreate?: Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_evento_id_fkeyInput | Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_evento_id_fkeyInput[]
  upsert?: Prisma.Eventos_IntegrantesUpsertWithWhereUniqueWithoutEventos_integrantes_evento_id_fkeyInput | Prisma.Eventos_IntegrantesUpsertWithWhereUniqueWithoutEventos_integrantes_evento_id_fkeyInput[]
  createMany?: Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_evento_id_fkeyInputEnvelope
  set?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  disconnect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  delete?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  connect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  update?: Prisma.Eventos_IntegrantesUpdateWithWhereUniqueWithoutEventos_integrantes_evento_id_fkeyInput | Prisma.Eventos_IntegrantesUpdateWithWhereUniqueWithoutEventos_integrantes_evento_id_fkeyInput[]
  updateMany?: Prisma.Eventos_IntegrantesUpdateManyWithWhereWithoutEventos_integrantes_evento_id_fkeyInput | Prisma.Eventos_IntegrantesUpdateManyWithWhereWithoutEventos_integrantes_evento_id_fkeyInput[]
  deleteMany?: Prisma.Eventos_IntegrantesScalarWhereInput | Prisma.Eventos_IntegrantesScalarWhereInput[]
}

export type Eventos_IntegrantesUncheckedUpdateManyWithoutEventos_integrantes_evento_id_fkeyNestedInput = {
  create?: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_evento_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_evento_id_fkeyInput> | Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_evento_id_fkeyInput[] | Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_evento_id_fkeyInput[]
  connectOrCreate?: Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_evento_id_fkeyInput | Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_evento_id_fkeyInput[]
  upsert?: Prisma.Eventos_IntegrantesUpsertWithWhereUniqueWithoutEventos_integrantes_evento_id_fkeyInput | Prisma.Eventos_IntegrantesUpsertWithWhereUniqueWithoutEventos_integrantes_evento_id_fkeyInput[]
  createMany?: Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_evento_id_fkeyInputEnvelope
  set?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  disconnect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  delete?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  connect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  update?: Prisma.Eventos_IntegrantesUpdateWithWhereUniqueWithoutEventos_integrantes_evento_id_fkeyInput | Prisma.Eventos_IntegrantesUpdateWithWhereUniqueWithoutEventos_integrantes_evento_id_fkeyInput[]
  updateMany?: Prisma.Eventos_IntegrantesUpdateManyWithWhereWithoutEventos_integrantes_evento_id_fkeyInput | Prisma.Eventos_IntegrantesUpdateManyWithWhereWithoutEventos_integrantes_evento_id_fkeyInput[]
  deleteMany?: Prisma.Eventos_IntegrantesScalarWhereInput | Prisma.Eventos_IntegrantesScalarWhereInput[]
}

export type Eventos_IntegrantesCreateNestedManyWithoutEventos_integrantes_musico_id_fkeyInput = {
  create?: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_musico_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_musico_id_fkeyInput> | Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_musico_id_fkeyInput[] | Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_musico_id_fkeyInput[]
  connectOrCreate?: Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_musico_id_fkeyInput | Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_musico_id_fkeyInput[]
  createMany?: Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_musico_id_fkeyInputEnvelope
  connect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
}

export type Eventos_IntegrantesUncheckedCreateNestedManyWithoutEventos_integrantes_musico_id_fkeyInput = {
  create?: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_musico_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_musico_id_fkeyInput> | Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_musico_id_fkeyInput[] | Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_musico_id_fkeyInput[]
  connectOrCreate?: Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_musico_id_fkeyInput | Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_musico_id_fkeyInput[]
  createMany?: Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_musico_id_fkeyInputEnvelope
  connect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
}

export type Eventos_IntegrantesUpdateManyWithoutEventos_integrantes_musico_id_fkeyNestedInput = {
  create?: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_musico_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_musico_id_fkeyInput> | Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_musico_id_fkeyInput[] | Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_musico_id_fkeyInput[]
  connectOrCreate?: Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_musico_id_fkeyInput | Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_musico_id_fkeyInput[]
  upsert?: Prisma.Eventos_IntegrantesUpsertWithWhereUniqueWithoutEventos_integrantes_musico_id_fkeyInput | Prisma.Eventos_IntegrantesUpsertWithWhereUniqueWithoutEventos_integrantes_musico_id_fkeyInput[]
  createMany?: Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_musico_id_fkeyInputEnvelope
  set?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  disconnect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  delete?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  connect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  update?: Prisma.Eventos_IntegrantesUpdateWithWhereUniqueWithoutEventos_integrantes_musico_id_fkeyInput | Prisma.Eventos_IntegrantesUpdateWithWhereUniqueWithoutEventos_integrantes_musico_id_fkeyInput[]
  updateMany?: Prisma.Eventos_IntegrantesUpdateManyWithWhereWithoutEventos_integrantes_musico_id_fkeyInput | Prisma.Eventos_IntegrantesUpdateManyWithWhereWithoutEventos_integrantes_musico_id_fkeyInput[]
  deleteMany?: Prisma.Eventos_IntegrantesScalarWhereInput | Prisma.Eventos_IntegrantesScalarWhereInput[]
}

export type Eventos_IntegrantesUncheckedUpdateManyWithoutEventos_integrantes_musico_id_fkeyNestedInput = {
  create?: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_musico_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_musico_id_fkeyInput> | Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_musico_id_fkeyInput[] | Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_musico_id_fkeyInput[]
  connectOrCreate?: Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_musico_id_fkeyInput | Prisma.Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_musico_id_fkeyInput[]
  upsert?: Prisma.Eventos_IntegrantesUpsertWithWhereUniqueWithoutEventos_integrantes_musico_id_fkeyInput | Prisma.Eventos_IntegrantesUpsertWithWhereUniqueWithoutEventos_integrantes_musico_id_fkeyInput[]
  createMany?: Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_musico_id_fkeyInputEnvelope
  set?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  disconnect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  delete?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  connect?: Prisma.Eventos_IntegrantesWhereUniqueInput | Prisma.Eventos_IntegrantesWhereUniqueInput[]
  update?: Prisma.Eventos_IntegrantesUpdateWithWhereUniqueWithoutEventos_integrantes_musico_id_fkeyInput | Prisma.Eventos_IntegrantesUpdateWithWhereUniqueWithoutEventos_integrantes_musico_id_fkeyInput[]
  updateMany?: Prisma.Eventos_IntegrantesUpdateManyWithWhereWithoutEventos_integrantes_musico_id_fkeyInput | Prisma.Eventos_IntegrantesUpdateManyWithWhereWithoutEventos_integrantes_musico_id_fkeyInput[]
  deleteMany?: Prisma.Eventos_IntegrantesScalarWhereInput | Prisma.Eventos_IntegrantesScalarWhereInput[]
}

export type Eventos_IntegrantesCreateWithoutEventos_integrantes_evento_id_fkeyInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  eventos_integrantes_musico_id_fkey: Prisma.IntegrantesCreateNestedOneWithoutEventos_IntegrantesInput
}

export type Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_evento_id_fkeyInput = {
  id?: string
  musico_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_evento_id_fkeyInput = {
  where: Prisma.Eventos_IntegrantesWhereUniqueInput
  create: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_evento_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_evento_id_fkeyInput>
}

export type Eventos_IntegrantesCreateManyEventos_integrantes_evento_id_fkeyInputEnvelope = {
  data: Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_evento_id_fkeyInput | Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_evento_id_fkeyInput[]
  skipDuplicates?: boolean
}

export type Eventos_IntegrantesUpsertWithWhereUniqueWithoutEventos_integrantes_evento_id_fkeyInput = {
  where: Prisma.Eventos_IntegrantesWhereUniqueInput
  update: Prisma.XOR<Prisma.Eventos_IntegrantesUpdateWithoutEventos_integrantes_evento_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedUpdateWithoutEventos_integrantes_evento_id_fkeyInput>
  create: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_evento_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_evento_id_fkeyInput>
}

export type Eventos_IntegrantesUpdateWithWhereUniqueWithoutEventos_integrantes_evento_id_fkeyInput = {
  where: Prisma.Eventos_IntegrantesWhereUniqueInput
  data: Prisma.XOR<Prisma.Eventos_IntegrantesUpdateWithoutEventos_integrantes_evento_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedUpdateWithoutEventos_integrantes_evento_id_fkeyInput>
}

export type Eventos_IntegrantesUpdateManyWithWhereWithoutEventos_integrantes_evento_id_fkeyInput = {
  where: Prisma.Eventos_IntegrantesScalarWhereInput
  data: Prisma.XOR<Prisma.Eventos_IntegrantesUpdateManyMutationInput, Prisma.Eventos_IntegrantesUncheckedUpdateManyWithoutEventos_integrantes_evento_id_fkeyInput>
}

export type Eventos_IntegrantesScalarWhereInput = {
  AND?: Prisma.Eventos_IntegrantesScalarWhereInput | Prisma.Eventos_IntegrantesScalarWhereInput[]
  OR?: Prisma.Eventos_IntegrantesScalarWhereInput[]
  NOT?: Prisma.Eventos_IntegrantesScalarWhereInput | Prisma.Eventos_IntegrantesScalarWhereInput[]
  id?: Prisma.UuidFilter<"Eventos_Integrantes"> | string
  evento_id?: Prisma.UuidFilter<"Eventos_Integrantes"> | string
  musico_id?: Prisma.UuidFilter<"Eventos_Integrantes"> | string
  created_at?: Prisma.DateTimeFilter<"Eventos_Integrantes"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Eventos_Integrantes"> | Date | string
}

export type Eventos_IntegrantesCreateWithoutEventos_integrantes_musico_id_fkeyInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  eventos_integrantes_evento_id_fkey: Prisma.EventosCreateNestedOneWithoutEventos_IntegrantesInput
}

export type Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_musico_id_fkeyInput = {
  id?: string
  evento_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Eventos_IntegrantesCreateOrConnectWithoutEventos_integrantes_musico_id_fkeyInput = {
  where: Prisma.Eventos_IntegrantesWhereUniqueInput
  create: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_musico_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_musico_id_fkeyInput>
}

export type Eventos_IntegrantesCreateManyEventos_integrantes_musico_id_fkeyInputEnvelope = {
  data: Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_musico_id_fkeyInput | Prisma.Eventos_IntegrantesCreateManyEventos_integrantes_musico_id_fkeyInput[]
  skipDuplicates?: boolean
}

export type Eventos_IntegrantesUpsertWithWhereUniqueWithoutEventos_integrantes_musico_id_fkeyInput = {
  where: Prisma.Eventos_IntegrantesWhereUniqueInput
  update: Prisma.XOR<Prisma.Eventos_IntegrantesUpdateWithoutEventos_integrantes_musico_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedUpdateWithoutEventos_integrantes_musico_id_fkeyInput>
  create: Prisma.XOR<Prisma.Eventos_IntegrantesCreateWithoutEventos_integrantes_musico_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedCreateWithoutEventos_integrantes_musico_id_fkeyInput>
}

export type Eventos_IntegrantesUpdateWithWhereUniqueWithoutEventos_integrantes_musico_id_fkeyInput = {
  where: Prisma.Eventos_IntegrantesWhereUniqueInput
  data: Prisma.XOR<Prisma.Eventos_IntegrantesUpdateWithoutEventos_integrantes_musico_id_fkeyInput, Prisma.Eventos_IntegrantesUncheckedUpdateWithoutEventos_integrantes_musico_id_fkeyInput>
}

export type Eventos_IntegrantesUpdateManyWithWhereWithoutEventos_integrantes_musico_id_fkeyInput = {
  where: Prisma.Eventos_IntegrantesScalarWhereInput
  data: Prisma.XOR<Prisma.Eventos_IntegrantesUpdateManyMutationInput, Prisma.Eventos_IntegrantesUncheckedUpdateManyWithoutEventos_integrantes_musico_id_fkeyInput>
}

export type Eventos_IntegrantesCreateManyEventos_integrantes_evento_id_fkeyInput = {
  id?: string
  musico_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Eventos_IntegrantesUpdateWithoutEventos_integrantes_evento_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventos_integrantes_musico_id_fkey?: Prisma.IntegrantesUpdateOneRequiredWithoutEventos_IntegrantesNestedInput
}

export type Eventos_IntegrantesUncheckedUpdateWithoutEventos_integrantes_evento_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  musico_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Eventos_IntegrantesUncheckedUpdateManyWithoutEventos_integrantes_evento_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  musico_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Eventos_IntegrantesCreateManyEventos_integrantes_musico_id_fkeyInput = {
  id?: string
  evento_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Eventos_IntegrantesUpdateWithoutEventos_integrantes_musico_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventos_integrantes_evento_id_fkey?: Prisma.EventosUpdateOneRequiredWithoutEventos_IntegrantesNestedInput
}

export type Eventos_IntegrantesUncheckedUpdateWithoutEventos_integrantes_musico_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  evento_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Eventos_IntegrantesUncheckedUpdateManyWithoutEventos_integrantes_musico_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  evento_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type Eventos_IntegrantesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  evento_id?: boolean
  musico_id?: boolean
  created_at?: boolean
  updated_at?: boolean
  eventos_integrantes_evento_id_fkey?: boolean | Prisma.EventosDefaultArgs<ExtArgs>
  eventos_integrantes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventos_Integrantes"]>

export type Eventos_IntegrantesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  evento_id?: boolean
  musico_id?: boolean
  created_at?: boolean
  updated_at?: boolean
  eventos_integrantes_evento_id_fkey?: boolean | Prisma.EventosDefaultArgs<ExtArgs>
  eventos_integrantes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventos_Integrantes"]>

export type Eventos_IntegrantesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  evento_id?: boolean
  musico_id?: boolean
  created_at?: boolean
  updated_at?: boolean
  eventos_integrantes_evento_id_fkey?: boolean | Prisma.EventosDefaultArgs<ExtArgs>
  eventos_integrantes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventos_Integrantes"]>

export type Eventos_IntegrantesSelectScalar = {
  id?: boolean
  evento_id?: boolean
  musico_id?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type Eventos_IntegrantesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "evento_id" | "musico_id" | "created_at" | "updated_at", ExtArgs["result"]["eventos_Integrantes"]>
export type Eventos_IntegrantesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eventos_integrantes_evento_id_fkey?: boolean | Prisma.EventosDefaultArgs<ExtArgs>
  eventos_integrantes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}
export type Eventos_IntegrantesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eventos_integrantes_evento_id_fkey?: boolean | Prisma.EventosDefaultArgs<ExtArgs>
  eventos_integrantes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}
export type Eventos_IntegrantesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eventos_integrantes_evento_id_fkey?: boolean | Prisma.EventosDefaultArgs<ExtArgs>
  eventos_integrantes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}

export type $Eventos_IntegrantesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Eventos_Integrantes"
  objects: {
    eventos_integrantes_evento_id_fkey: Prisma.$EventosPayload<ExtArgs>
    eventos_integrantes_musico_id_fkey: Prisma.$IntegrantesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    evento_id: string
    musico_id: string
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["eventos_Integrantes"]>
  composites: {}
}

export type Eventos_IntegrantesGetPayload<S extends boolean | null | undefined | Eventos_IntegrantesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload, S>

export type Eventos_IntegrantesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<Eventos_IntegrantesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Eventos_IntegrantesCountAggregateInputType | true
  }

export interface Eventos_IntegrantesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Eventos_Integrantes'], meta: { name: 'Eventos_Integrantes' } }
  /**
   * Find zero or one Eventos_Integrantes that matches the filter.
   * @param {Eventos_IntegrantesFindUniqueArgs} args - Arguments to find a Eventos_Integrantes
   * @example
   * // Get one Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends Eventos_IntegrantesFindUniqueArgs>(args: Prisma.SelectSubset<T, Eventos_IntegrantesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__Eventos_IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Eventos_Integrantes that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {Eventos_IntegrantesFindUniqueOrThrowArgs} args - Arguments to find a Eventos_Integrantes
   * @example
   * // Get one Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends Eventos_IntegrantesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Eventos_IntegrantesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__Eventos_IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Eventos_Integrantes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Eventos_IntegrantesFindFirstArgs} args - Arguments to find a Eventos_Integrantes
   * @example
   * // Get one Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends Eventos_IntegrantesFindFirstArgs>(args?: Prisma.SelectSubset<T, Eventos_IntegrantesFindFirstArgs<ExtArgs>>): Prisma.Prisma__Eventos_IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Eventos_Integrantes that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Eventos_IntegrantesFindFirstOrThrowArgs} args - Arguments to find a Eventos_Integrantes
   * @example
   * // Get one Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends Eventos_IntegrantesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, Eventos_IntegrantesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__Eventos_IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Eventos_Integrantes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Eventos_IntegrantesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.findMany()
   * 
   * // Get first 10 Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventos_IntegrantesWithIdOnly = await prisma.eventos_Integrantes.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends Eventos_IntegrantesFindManyArgs>(args?: Prisma.SelectSubset<T, Eventos_IntegrantesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Eventos_Integrantes.
   * @param {Eventos_IntegrantesCreateArgs} args - Arguments to create a Eventos_Integrantes.
   * @example
   * // Create one Eventos_Integrantes
   * const Eventos_Integrantes = await prisma.eventos_Integrantes.create({
   *   data: {
   *     // ... data to create a Eventos_Integrantes
   *   }
   * })
   * 
   */
  create<T extends Eventos_IntegrantesCreateArgs>(args: Prisma.SelectSubset<T, Eventos_IntegrantesCreateArgs<ExtArgs>>): Prisma.Prisma__Eventos_IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Eventos_Integrantes.
   * @param {Eventos_IntegrantesCreateManyArgs} args - Arguments to create many Eventos_Integrantes.
   * @example
   * // Create many Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends Eventos_IntegrantesCreateManyArgs>(args?: Prisma.SelectSubset<T, Eventos_IntegrantesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Eventos_Integrantes and returns the data saved in the database.
   * @param {Eventos_IntegrantesCreateManyAndReturnArgs} args - Arguments to create many Eventos_Integrantes.
   * @example
   * // Create many Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Eventos_Integrantes and only return the `id`
   * const eventos_IntegrantesWithIdOnly = await prisma.eventos_Integrantes.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends Eventos_IntegrantesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, Eventos_IntegrantesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Eventos_Integrantes.
   * @param {Eventos_IntegrantesDeleteArgs} args - Arguments to delete one Eventos_Integrantes.
   * @example
   * // Delete one Eventos_Integrantes
   * const Eventos_Integrantes = await prisma.eventos_Integrantes.delete({
   *   where: {
   *     // ... filter to delete one Eventos_Integrantes
   *   }
   * })
   * 
   */
  delete<T extends Eventos_IntegrantesDeleteArgs>(args: Prisma.SelectSubset<T, Eventos_IntegrantesDeleteArgs<ExtArgs>>): Prisma.Prisma__Eventos_IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Eventos_Integrantes.
   * @param {Eventos_IntegrantesUpdateArgs} args - Arguments to update one Eventos_Integrantes.
   * @example
   * // Update one Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends Eventos_IntegrantesUpdateArgs>(args: Prisma.SelectSubset<T, Eventos_IntegrantesUpdateArgs<ExtArgs>>): Prisma.Prisma__Eventos_IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Eventos_Integrantes.
   * @param {Eventos_IntegrantesDeleteManyArgs} args - Arguments to filter Eventos_Integrantes to delete.
   * @example
   * // Delete a few Eventos_Integrantes
   * const { count } = await prisma.eventos_Integrantes.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends Eventos_IntegrantesDeleteManyArgs>(args?: Prisma.SelectSubset<T, Eventos_IntegrantesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Eventos_Integrantes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Eventos_IntegrantesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends Eventos_IntegrantesUpdateManyArgs>(args: Prisma.SelectSubset<T, Eventos_IntegrantesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Eventos_Integrantes and returns the data updated in the database.
   * @param {Eventos_IntegrantesUpdateManyAndReturnArgs} args - Arguments to update many Eventos_Integrantes.
   * @example
   * // Update many Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Eventos_Integrantes and only return the `id`
   * const eventos_IntegrantesWithIdOnly = await prisma.eventos_Integrantes.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends Eventos_IntegrantesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Eventos_IntegrantesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Eventos_Integrantes.
   * @param {Eventos_IntegrantesUpsertArgs} args - Arguments to update or create a Eventos_Integrantes.
   * @example
   * // Update or create a Eventos_Integrantes
   * const eventos_Integrantes = await prisma.eventos_Integrantes.upsert({
   *   create: {
   *     // ... data to create a Eventos_Integrantes
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Eventos_Integrantes we want to update
   *   }
   * })
   */
  upsert<T extends Eventos_IntegrantesUpsertArgs>(args: Prisma.SelectSubset<T, Eventos_IntegrantesUpsertArgs<ExtArgs>>): Prisma.Prisma__Eventos_IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Eventos_Integrantes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Eventos_IntegrantesCountArgs} args - Arguments to filter Eventos_Integrantes to count.
   * @example
   * // Count the number of Eventos_Integrantes
   * const count = await prisma.eventos_Integrantes.count({
   *   where: {
   *     // ... the filter for the Eventos_Integrantes we want to count
   *   }
   * })
  **/
  count<T extends Eventos_IntegrantesCountArgs>(
    args?: Prisma.Subset<T, Eventos_IntegrantesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Eventos_IntegrantesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Eventos_Integrantes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Eventos_IntegrantesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Eventos_IntegrantesAggregateArgs>(args: Prisma.Subset<T, Eventos_IntegrantesAggregateArgs>): Prisma.PrismaPromise<GetEventos_IntegrantesAggregateType<T>>

  /**
   * Group by Eventos_Integrantes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Eventos_IntegrantesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends Eventos_IntegrantesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: Eventos_IntegrantesGroupByArgs['orderBy'] }
      : { orderBy?: Eventos_IntegrantesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, Eventos_IntegrantesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventos_IntegrantesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Eventos_Integrantes model
 */
readonly fields: Eventos_IntegrantesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Eventos_Integrantes.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__Eventos_IntegrantesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  eventos_integrantes_evento_id_fkey<T extends Prisma.EventosDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventosDefaultArgs<ExtArgs>>): Prisma.Prisma__EventosClient<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  eventos_integrantes_musico_id_fkey<T extends Prisma.IntegrantesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.IntegrantesDefaultArgs<ExtArgs>>): Prisma.Prisma__IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Eventos_Integrantes model
 */
export interface Eventos_IntegrantesFieldRefs {
  readonly id: Prisma.FieldRef<"Eventos_Integrantes", 'String'>
  readonly evento_id: Prisma.FieldRef<"Eventos_Integrantes", 'String'>
  readonly musico_id: Prisma.FieldRef<"Eventos_Integrantes", 'String'>
  readonly created_at: Prisma.FieldRef<"Eventos_Integrantes", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Eventos_Integrantes", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Eventos_Integrantes findUnique
 */
export type Eventos_IntegrantesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
  /**
   * Filter, which Eventos_Integrantes to fetch.
   */
  where: Prisma.Eventos_IntegrantesWhereUniqueInput
}

/**
 * Eventos_Integrantes findUniqueOrThrow
 */
export type Eventos_IntegrantesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
  /**
   * Filter, which Eventos_Integrantes to fetch.
   */
  where: Prisma.Eventos_IntegrantesWhereUniqueInput
}

/**
 * Eventos_Integrantes findFirst
 */
export type Eventos_IntegrantesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
  /**
   * Filter, which Eventos_Integrantes to fetch.
   */
  where?: Prisma.Eventos_IntegrantesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Eventos_Integrantes to fetch.
   */
  orderBy?: Prisma.Eventos_IntegrantesOrderByWithRelationInput | Prisma.Eventos_IntegrantesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Eventos_Integrantes.
   */
  cursor?: Prisma.Eventos_IntegrantesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Eventos_Integrantes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Eventos_Integrantes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Eventos_Integrantes.
   */
  distinct?: Prisma.Eventos_IntegrantesScalarFieldEnum | Prisma.Eventos_IntegrantesScalarFieldEnum[]
}

/**
 * Eventos_Integrantes findFirstOrThrow
 */
export type Eventos_IntegrantesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
  /**
   * Filter, which Eventos_Integrantes to fetch.
   */
  where?: Prisma.Eventos_IntegrantesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Eventos_Integrantes to fetch.
   */
  orderBy?: Prisma.Eventos_IntegrantesOrderByWithRelationInput | Prisma.Eventos_IntegrantesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Eventos_Integrantes.
   */
  cursor?: Prisma.Eventos_IntegrantesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Eventos_Integrantes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Eventos_Integrantes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Eventos_Integrantes.
   */
  distinct?: Prisma.Eventos_IntegrantesScalarFieldEnum | Prisma.Eventos_IntegrantesScalarFieldEnum[]
}

/**
 * Eventos_Integrantes findMany
 */
export type Eventos_IntegrantesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
  /**
   * Filter, which Eventos_Integrantes to fetch.
   */
  where?: Prisma.Eventos_IntegrantesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Eventos_Integrantes to fetch.
   */
  orderBy?: Prisma.Eventos_IntegrantesOrderByWithRelationInput | Prisma.Eventos_IntegrantesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Eventos_Integrantes.
   */
  cursor?: Prisma.Eventos_IntegrantesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Eventos_Integrantes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Eventos_Integrantes.
   */
  skip?: number
  distinct?: Prisma.Eventos_IntegrantesScalarFieldEnum | Prisma.Eventos_IntegrantesScalarFieldEnum[]
}

/**
 * Eventos_Integrantes create
 */
export type Eventos_IntegrantesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
  /**
   * The data needed to create a Eventos_Integrantes.
   */
  data: Prisma.XOR<Prisma.Eventos_IntegrantesCreateInput, Prisma.Eventos_IntegrantesUncheckedCreateInput>
}

/**
 * Eventos_Integrantes createMany
 */
export type Eventos_IntegrantesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Eventos_Integrantes.
   */
  data: Prisma.Eventos_IntegrantesCreateManyInput | Prisma.Eventos_IntegrantesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Eventos_Integrantes createManyAndReturn
 */
export type Eventos_IntegrantesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * The data used to create many Eventos_Integrantes.
   */
  data: Prisma.Eventos_IntegrantesCreateManyInput | Prisma.Eventos_IntegrantesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Eventos_Integrantes update
 */
export type Eventos_IntegrantesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
  /**
   * The data needed to update a Eventos_Integrantes.
   */
  data: Prisma.XOR<Prisma.Eventos_IntegrantesUpdateInput, Prisma.Eventos_IntegrantesUncheckedUpdateInput>
  /**
   * Choose, which Eventos_Integrantes to update.
   */
  where: Prisma.Eventos_IntegrantesWhereUniqueInput
}

/**
 * Eventos_Integrantes updateMany
 */
export type Eventos_IntegrantesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Eventos_Integrantes.
   */
  data: Prisma.XOR<Prisma.Eventos_IntegrantesUpdateManyMutationInput, Prisma.Eventos_IntegrantesUncheckedUpdateManyInput>
  /**
   * Filter which Eventos_Integrantes to update
   */
  where?: Prisma.Eventos_IntegrantesWhereInput
  /**
   * Limit how many Eventos_Integrantes to update.
   */
  limit?: number
}

/**
 * Eventos_Integrantes updateManyAndReturn
 */
export type Eventos_IntegrantesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * The data used to update Eventos_Integrantes.
   */
  data: Prisma.XOR<Prisma.Eventos_IntegrantesUpdateManyMutationInput, Prisma.Eventos_IntegrantesUncheckedUpdateManyInput>
  /**
   * Filter which Eventos_Integrantes to update
   */
  where?: Prisma.Eventos_IntegrantesWhereInput
  /**
   * Limit how many Eventos_Integrantes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Eventos_Integrantes upsert
 */
export type Eventos_IntegrantesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
  /**
   * The filter to search for the Eventos_Integrantes to update in case it exists.
   */
  where: Prisma.Eventos_IntegrantesWhereUniqueInput
  /**
   * In case the Eventos_Integrantes found by the `where` argument doesn't exist, create a new Eventos_Integrantes with this data.
   */
  create: Prisma.XOR<Prisma.Eventos_IntegrantesCreateInput, Prisma.Eventos_IntegrantesUncheckedCreateInput>
  /**
   * In case the Eventos_Integrantes was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.Eventos_IntegrantesUpdateInput, Prisma.Eventos_IntegrantesUncheckedUpdateInput>
}

/**
 * Eventos_Integrantes delete
 */
export type Eventos_IntegrantesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
  /**
   * Filter which Eventos_Integrantes to delete.
   */
  where: Prisma.Eventos_IntegrantesWhereUniqueInput
}

/**
 * Eventos_Integrantes deleteMany
 */
export type Eventos_IntegrantesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Eventos_Integrantes to delete
   */
  where?: Prisma.Eventos_IntegrantesWhereInput
  /**
   * Limit how many Eventos_Integrantes to delete.
   */
  limit?: number
}

/**
 * Eventos_Integrantes without action
 */
export type Eventos_IntegrantesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
}
