
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Eventos` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Eventos
 * 
 */
export type EventosModel = runtime.Types.Result.DefaultSelection<Prisma.$EventosPayload>

export type AggregateEventos = {
  _count: EventosCountAggregateOutputType | null
  _min: EventosMinAggregateOutputType | null
  _max: EventosMaxAggregateOutputType | null
}

export type EventosMinAggregateOutputType = {
  id: string | null
  data: Date | null
  fk_tipo_evento: string | null
  descricao: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type EventosMaxAggregateOutputType = {
  id: string | null
  data: Date | null
  fk_tipo_evento: string | null
  descricao: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type EventosCountAggregateOutputType = {
  id: number
  data: number
  fk_tipo_evento: number
  descricao: number
  created_at: number
  updated_at: number
  _all: number
}


export type EventosMinAggregateInputType = {
  id?: true
  data?: true
  fk_tipo_evento?: true
  descricao?: true
  created_at?: true
  updated_at?: true
}

export type EventosMaxAggregateInputType = {
  id?: true
  data?: true
  fk_tipo_evento?: true
  descricao?: true
  created_at?: true
  updated_at?: true
}

export type EventosCountAggregateInputType = {
  id?: true
  data?: true
  fk_tipo_evento?: true
  descricao?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type EventosAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Eventos to aggregate.
   */
  where?: Prisma.EventosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Eventos to fetch.
   */
  orderBy?: Prisma.EventosOrderByWithRelationInput | Prisma.EventosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Eventos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Eventos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Eventos
  **/
  _count?: true | EventosCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventosMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventosMaxAggregateInputType
}

export type GetEventosAggregateType<T extends EventosAggregateArgs> = {
      [P in keyof T & keyof AggregateEventos]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventos[P]>
    : Prisma.GetScalarType<T[P], AggregateEventos[P]>
}




export type EventosGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventosWhereInput
  orderBy?: Prisma.EventosOrderByWithAggregationInput | Prisma.EventosOrderByWithAggregationInput[]
  by: Prisma.EventosScalarFieldEnum[] | Prisma.EventosScalarFieldEnum
  having?: Prisma.EventosScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventosCountAggregateInputType | true
  _min?: EventosMinAggregateInputType
  _max?: EventosMaxAggregateInputType
}

export type EventosGroupByOutputType = {
  id: string
  data: Date
  fk_tipo_evento: string
  descricao: string
  created_at: Date
  updated_at: Date
  _count: EventosCountAggregateOutputType | null
  _min: EventosMinAggregateOutputType | null
  _max: EventosMaxAggregateOutputType | null
}

type GetEventosGroupByPayload<T extends EventosGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventosGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventosGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventosGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventosGroupByOutputType[P]>
      }
    >
  >



export type EventosWhereInput = {
  AND?: Prisma.EventosWhereInput | Prisma.EventosWhereInput[]
  OR?: Prisma.EventosWhereInput[]
  NOT?: Prisma.EventosWhereInput | Prisma.EventosWhereInput[]
  id?: Prisma.UuidFilter<"Eventos"> | string
  data?: Prisma.DateTimeFilter<"Eventos"> | Date | string
  fk_tipo_evento?: Prisma.UuidFilter<"Eventos"> | string
  descricao?: Prisma.StringFilter<"Eventos"> | string
  created_at?: Prisma.DateTimeFilter<"Eventos"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Eventos"> | Date | string
  eventos_fk_tipo_evento_fkey?: Prisma.XOR<Prisma.Tipos_EventosScalarRelationFilter, Prisma.Tipos_EventosWhereInput>
  Eventos_Musicas?: Prisma.Eventos_MusicasListRelationFilter
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesListRelationFilter
}

export type EventosOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  fk_tipo_evento?: Prisma.SortOrder
  descricao?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  eventos_fk_tipo_evento_fkey?: Prisma.Tipos_EventosOrderByWithRelationInput
  Eventos_Musicas?: Prisma.Eventos_MusicasOrderByRelationAggregateInput
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesOrderByRelationAggregateInput
}

export type EventosWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EventosWhereInput | Prisma.EventosWhereInput[]
  OR?: Prisma.EventosWhereInput[]
  NOT?: Prisma.EventosWhereInput | Prisma.EventosWhereInput[]
  data?: Prisma.DateTimeFilter<"Eventos"> | Date | string
  fk_tipo_evento?: Prisma.UuidFilter<"Eventos"> | string
  descricao?: Prisma.StringFilter<"Eventos"> | string
  created_at?: Prisma.DateTimeFilter<"Eventos"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Eventos"> | Date | string
  eventos_fk_tipo_evento_fkey?: Prisma.XOR<Prisma.Tipos_EventosScalarRelationFilter, Prisma.Tipos_EventosWhereInput>
  Eventos_Musicas?: Prisma.Eventos_MusicasListRelationFilter
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesListRelationFilter
}, "id">

export type EventosOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  fk_tipo_evento?: Prisma.SortOrder
  descricao?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.EventosCountOrderByAggregateInput
  _max?: Prisma.EventosMaxOrderByAggregateInput
  _min?: Prisma.EventosMinOrderByAggregateInput
}

export type EventosScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventosScalarWhereWithAggregatesInput | Prisma.EventosScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventosScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventosScalarWhereWithAggregatesInput | Prisma.EventosScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Eventos"> | string
  data?: Prisma.DateTimeWithAggregatesFilter<"Eventos"> | Date | string
  fk_tipo_evento?: Prisma.UuidWithAggregatesFilter<"Eventos"> | string
  descricao?: Prisma.StringWithAggregatesFilter<"Eventos"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Eventos"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Eventos"> | Date | string
}

export type EventosCreateInput = {
  id?: string
  data: Date | string
  descricao: string
  created_at?: Date | string
  updated_at?: Date | string
  eventos_fk_tipo_evento_fkey: Prisma.Tipos_EventosCreateNestedOneWithoutEventosInput
  Eventos_Musicas?: Prisma.Eventos_MusicasCreateNestedManyWithoutEventos_musicas_evento_id_fkeyInput
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesCreateNestedManyWithoutEventos_integrantes_evento_id_fkeyInput
}

export type EventosUncheckedCreateInput = {
  id?: string
  data: Date | string
  fk_tipo_evento: string
  descricao: string
  created_at?: Date | string
  updated_at?: Date | string
  Eventos_Musicas?: Prisma.Eventos_MusicasUncheckedCreateNestedManyWithoutEventos_musicas_evento_id_fkeyInput
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUncheckedCreateNestedManyWithoutEventos_integrantes_evento_id_fkeyInput
}

export type EventosUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  descricao?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventos_fk_tipo_evento_fkey?: Prisma.Tipos_EventosUpdateOneRequiredWithoutEventosNestedInput
  Eventos_Musicas?: Prisma.Eventos_MusicasUpdateManyWithoutEventos_musicas_evento_id_fkeyNestedInput
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUpdateManyWithoutEventos_integrantes_evento_id_fkeyNestedInput
}

export type EventosUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fk_tipo_evento?: Prisma.StringFieldUpdateOperationsInput | string
  descricao?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Eventos_Musicas?: Prisma.Eventos_MusicasUncheckedUpdateManyWithoutEventos_musicas_evento_id_fkeyNestedInput
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUncheckedUpdateManyWithoutEventos_integrantes_evento_id_fkeyNestedInput
}

export type EventosCreateManyInput = {
  id?: string
  data: Date | string
  fk_tipo_evento: string
  descricao: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type EventosUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  descricao?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventosUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fk_tipo_evento?: Prisma.StringFieldUpdateOperationsInput | string
  descricao?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventosCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  fk_tipo_evento?: Prisma.SortOrder
  descricao?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type EventosMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  fk_tipo_evento?: Prisma.SortOrder
  descricao?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type EventosMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  data?: Prisma.SortOrder
  fk_tipo_evento?: Prisma.SortOrder
  descricao?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type EventosScalarRelationFilter = {
  is?: Prisma.EventosWhereInput
  isNot?: Prisma.EventosWhereInput
}

export type EventosListRelationFilter = {
  every?: Prisma.EventosWhereInput
  some?: Prisma.EventosWhereInput
  none?: Prisma.EventosWhereInput
}

export type EventosOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EventosCreateNestedOneWithoutEventos_MusicasInput = {
  create?: Prisma.XOR<Prisma.EventosCreateWithoutEventos_MusicasInput, Prisma.EventosUncheckedCreateWithoutEventos_MusicasInput>
  connectOrCreate?: Prisma.EventosCreateOrConnectWithoutEventos_MusicasInput
  connect?: Prisma.EventosWhereUniqueInput
}

export type EventosUpdateOneRequiredWithoutEventos_MusicasNestedInput = {
  create?: Prisma.XOR<Prisma.EventosCreateWithoutEventos_MusicasInput, Prisma.EventosUncheckedCreateWithoutEventos_MusicasInput>
  connectOrCreate?: Prisma.EventosCreateOrConnectWithoutEventos_MusicasInput
  upsert?: Prisma.EventosUpsertWithoutEventos_MusicasInput
  connect?: Prisma.EventosWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventosUpdateToOneWithWhereWithoutEventos_MusicasInput, Prisma.EventosUpdateWithoutEventos_MusicasInput>, Prisma.EventosUncheckedUpdateWithoutEventos_MusicasInput>
}

export type EventosCreateNestedOneWithoutEventos_IntegrantesInput = {
  create?: Prisma.XOR<Prisma.EventosCreateWithoutEventos_IntegrantesInput, Prisma.EventosUncheckedCreateWithoutEventos_IntegrantesInput>
  connectOrCreate?: Prisma.EventosCreateOrConnectWithoutEventos_IntegrantesInput
  connect?: Prisma.EventosWhereUniqueInput
}

export type EventosUpdateOneRequiredWithoutEventos_IntegrantesNestedInput = {
  create?: Prisma.XOR<Prisma.EventosCreateWithoutEventos_IntegrantesInput, Prisma.EventosUncheckedCreateWithoutEventos_IntegrantesInput>
  connectOrCreate?: Prisma.EventosCreateOrConnectWithoutEventos_IntegrantesInput
  upsert?: Prisma.EventosUpsertWithoutEventos_IntegrantesInput
  connect?: Prisma.EventosWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventosUpdateToOneWithWhereWithoutEventos_IntegrantesInput, Prisma.EventosUpdateWithoutEventos_IntegrantesInput>, Prisma.EventosUncheckedUpdateWithoutEventos_IntegrantesInput>
}

export type EventosCreateNestedManyWithoutEventos_fk_tipo_evento_fkeyInput = {
  create?: Prisma.XOR<Prisma.EventosCreateWithoutEventos_fk_tipo_evento_fkeyInput, Prisma.EventosUncheckedCreateWithoutEventos_fk_tipo_evento_fkeyInput> | Prisma.EventosCreateWithoutEventos_fk_tipo_evento_fkeyInput[] | Prisma.EventosUncheckedCreateWithoutEventos_fk_tipo_evento_fkeyInput[]
  connectOrCreate?: Prisma.EventosCreateOrConnectWithoutEventos_fk_tipo_evento_fkeyInput | Prisma.EventosCreateOrConnectWithoutEventos_fk_tipo_evento_fkeyInput[]
  createMany?: Prisma.EventosCreateManyEventos_fk_tipo_evento_fkeyInputEnvelope
  connect?: Prisma.EventosWhereUniqueInput | Prisma.EventosWhereUniqueInput[]
}

export type EventosUncheckedCreateNestedManyWithoutEventos_fk_tipo_evento_fkeyInput = {
  create?: Prisma.XOR<Prisma.EventosCreateWithoutEventos_fk_tipo_evento_fkeyInput, Prisma.EventosUncheckedCreateWithoutEventos_fk_tipo_evento_fkeyInput> | Prisma.EventosCreateWithoutEventos_fk_tipo_evento_fkeyInput[] | Prisma.EventosUncheckedCreateWithoutEventos_fk_tipo_evento_fkeyInput[]
  connectOrCreate?: Prisma.EventosCreateOrConnectWithoutEventos_fk_tipo_evento_fkeyInput | Prisma.EventosCreateOrConnectWithoutEventos_fk_tipo_evento_fkeyInput[]
  createMany?: Prisma.EventosCreateManyEventos_fk_tipo_evento_fkeyInputEnvelope
  connect?: Prisma.EventosWhereUniqueInput | Prisma.EventosWhereUniqueInput[]
}

export type EventosUpdateManyWithoutEventos_fk_tipo_evento_fkeyNestedInput = {
  create?: Prisma.XOR<Prisma.EventosCreateWithoutEventos_fk_tipo_evento_fkeyInput, Prisma.EventosUncheckedCreateWithoutEventos_fk_tipo_evento_fkeyInput> | Prisma.EventosCreateWithoutEventos_fk_tipo_evento_fkeyInput[] | Prisma.EventosUncheckedCreateWithoutEventos_fk_tipo_evento_fkeyInput[]
  connectOrCreate?: Prisma.EventosCreateOrConnectWithoutEventos_fk_tipo_evento_fkeyInput | Prisma.EventosCreateOrConnectWithoutEventos_fk_tipo_evento_fkeyInput[]
  upsert?: Prisma.EventosUpsertWithWhereUniqueWithoutEventos_fk_tipo_evento_fkeyInput | Prisma.EventosUpsertWithWhereUniqueWithoutEventos_fk_tipo_evento_fkeyInput[]
  createMany?: Prisma.EventosCreateManyEventos_fk_tipo_evento_fkeyInputEnvelope
  set?: Prisma.EventosWhereUniqueInput | Prisma.EventosWhereUniqueInput[]
  disconnect?: Prisma.EventosWhereUniqueInput | Prisma.EventosWhereUniqueInput[]
  delete?: Prisma.EventosWhereUniqueInput | Prisma.EventosWhereUniqueInput[]
  connect?: Prisma.EventosWhereUniqueInput | Prisma.EventosWhereUniqueInput[]
  update?: Prisma.EventosUpdateWithWhereUniqueWithoutEventos_fk_tipo_evento_fkeyInput | Prisma.EventosUpdateWithWhereUniqueWithoutEventos_fk_tipo_evento_fkeyInput[]
  updateMany?: Prisma.EventosUpdateManyWithWhereWithoutEventos_fk_tipo_evento_fkeyInput | Prisma.EventosUpdateManyWithWhereWithoutEventos_fk_tipo_evento_fkeyInput[]
  deleteMany?: Prisma.EventosScalarWhereInput | Prisma.EventosScalarWhereInput[]
}

export type EventosUncheckedUpdateManyWithoutEventos_fk_tipo_evento_fkeyNestedInput = {
  create?: Prisma.XOR<Prisma.EventosCreateWithoutEventos_fk_tipo_evento_fkeyInput, Prisma.EventosUncheckedCreateWithoutEventos_fk_tipo_evento_fkeyInput> | Prisma.EventosCreateWithoutEventos_fk_tipo_evento_fkeyInput[] | Prisma.EventosUncheckedCreateWithoutEventos_fk_tipo_evento_fkeyInput[]
  connectOrCreate?: Prisma.EventosCreateOrConnectWithoutEventos_fk_tipo_evento_fkeyInput | Prisma.EventosCreateOrConnectWithoutEventos_fk_tipo_evento_fkeyInput[]
  upsert?: Prisma.EventosUpsertWithWhereUniqueWithoutEventos_fk_tipo_evento_fkeyInput | Prisma.EventosUpsertWithWhereUniqueWithoutEventos_fk_tipo_evento_fkeyInput[]
  createMany?: Prisma.EventosCreateManyEventos_fk_tipo_evento_fkeyInputEnvelope
  set?: Prisma.EventosWhereUniqueInput | Prisma.EventosWhereUniqueInput[]
  disconnect?: Prisma.EventosWhereUniqueInput | Prisma.EventosWhereUniqueInput[]
  delete?: Prisma.EventosWhereUniqueInput | Prisma.EventosWhereUniqueInput[]
  connect?: Prisma.EventosWhereUniqueInput | Prisma.EventosWhereUniqueInput[]
  update?: Prisma.EventosUpdateWithWhereUniqueWithoutEventos_fk_tipo_evento_fkeyInput | Prisma.EventosUpdateWithWhereUniqueWithoutEventos_fk_tipo_evento_fkeyInput[]
  updateMany?: Prisma.EventosUpdateManyWithWhereWithoutEventos_fk_tipo_evento_fkeyInput | Prisma.EventosUpdateManyWithWhereWithoutEventos_fk_tipo_evento_fkeyInput[]
  deleteMany?: Prisma.EventosScalarWhereInput | Prisma.EventosScalarWhereInput[]
}

export type EventosCreateWithoutEventos_MusicasInput = {
  id?: string
  data: Date | string
  descricao: string
  created_at?: Date | string
  updated_at?: Date | string
  eventos_fk_tipo_evento_fkey: Prisma.Tipos_EventosCreateNestedOneWithoutEventosInput
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesCreateNestedManyWithoutEventos_integrantes_evento_id_fkeyInput
}

export type EventosUncheckedCreateWithoutEventos_MusicasInput = {
  id?: string
  data: Date | string
  fk_tipo_evento: string
  descricao: string
  created_at?: Date | string
  updated_at?: Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUncheckedCreateNestedManyWithoutEventos_integrantes_evento_id_fkeyInput
}

export type EventosCreateOrConnectWithoutEventos_MusicasInput = {
  where: Prisma.EventosWhereUniqueInput
  create: Prisma.XOR<Prisma.EventosCreateWithoutEventos_MusicasInput, Prisma.EventosUncheckedCreateWithoutEventos_MusicasInput>
}

export type EventosUpsertWithoutEventos_MusicasInput = {
  update: Prisma.XOR<Prisma.EventosUpdateWithoutEventos_MusicasInput, Prisma.EventosUncheckedUpdateWithoutEventos_MusicasInput>
  create: Prisma.XOR<Prisma.EventosCreateWithoutEventos_MusicasInput, Prisma.EventosUncheckedCreateWithoutEventos_MusicasInput>
  where?: Prisma.EventosWhereInput
}

export type EventosUpdateToOneWithWhereWithoutEventos_MusicasInput = {
  where?: Prisma.EventosWhereInput
  data: Prisma.XOR<Prisma.EventosUpdateWithoutEventos_MusicasInput, Prisma.EventosUncheckedUpdateWithoutEventos_MusicasInput>
}

export type EventosUpdateWithoutEventos_MusicasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  descricao?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventos_fk_tipo_evento_fkey?: Prisma.Tipos_EventosUpdateOneRequiredWithoutEventosNestedInput
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUpdateManyWithoutEventos_integrantes_evento_id_fkeyNestedInput
}

export type EventosUncheckedUpdateWithoutEventos_MusicasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fk_tipo_evento?: Prisma.StringFieldUpdateOperationsInput | string
  descricao?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUncheckedUpdateManyWithoutEventos_integrantes_evento_id_fkeyNestedInput
}

export type EventosCreateWithoutEventos_IntegrantesInput = {
  id?: string
  data: Date | string
  descricao: string
  created_at?: Date | string
  updated_at?: Date | string
  eventos_fk_tipo_evento_fkey: Prisma.Tipos_EventosCreateNestedOneWithoutEventosInput
  Eventos_Musicas?: Prisma.Eventos_MusicasCreateNestedManyWithoutEventos_musicas_evento_id_fkeyInput
}

export type EventosUncheckedCreateWithoutEventos_IntegrantesInput = {
  id?: string
  data: Date | string
  fk_tipo_evento: string
  descricao: string
  created_at?: Date | string
  updated_at?: Date | string
  Eventos_Musicas?: Prisma.Eventos_MusicasUncheckedCreateNestedManyWithoutEventos_musicas_evento_id_fkeyInput
}

export type EventosCreateOrConnectWithoutEventos_IntegrantesInput = {
  where: Prisma.EventosWhereUniqueInput
  create: Prisma.XOR<Prisma.EventosCreateWithoutEventos_IntegrantesInput, Prisma.EventosUncheckedCreateWithoutEventos_IntegrantesInput>
}

export type EventosUpsertWithoutEventos_IntegrantesInput = {
  update: Prisma.XOR<Prisma.EventosUpdateWithoutEventos_IntegrantesInput, Prisma.EventosUncheckedUpdateWithoutEventos_IntegrantesInput>
  create: Prisma.XOR<Prisma.EventosCreateWithoutEventos_IntegrantesInput, Prisma.EventosUncheckedCreateWithoutEventos_IntegrantesInput>
  where?: Prisma.EventosWhereInput
}

export type EventosUpdateToOneWithWhereWithoutEventos_IntegrantesInput = {
  where?: Prisma.EventosWhereInput
  data: Prisma.XOR<Prisma.EventosUpdateWithoutEventos_IntegrantesInput, Prisma.EventosUncheckedUpdateWithoutEventos_IntegrantesInput>
}

export type EventosUpdateWithoutEventos_IntegrantesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  descricao?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  eventos_fk_tipo_evento_fkey?: Prisma.Tipos_EventosUpdateOneRequiredWithoutEventosNestedInput
  Eventos_Musicas?: Prisma.Eventos_MusicasUpdateManyWithoutEventos_musicas_evento_id_fkeyNestedInput
}

export type EventosUncheckedUpdateWithoutEventos_IntegrantesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fk_tipo_evento?: Prisma.StringFieldUpdateOperationsInput | string
  descricao?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Eventos_Musicas?: Prisma.Eventos_MusicasUncheckedUpdateManyWithoutEventos_musicas_evento_id_fkeyNestedInput
}

export type EventosCreateWithoutEventos_fk_tipo_evento_fkeyInput = {
  id?: string
  data: Date | string
  descricao: string
  created_at?: Date | string
  updated_at?: Date | string
  Eventos_Musicas?: Prisma.Eventos_MusicasCreateNestedManyWithoutEventos_musicas_evento_id_fkeyInput
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesCreateNestedManyWithoutEventos_integrantes_evento_id_fkeyInput
}

export type EventosUncheckedCreateWithoutEventos_fk_tipo_evento_fkeyInput = {
  id?: string
  data: Date | string
  descricao: string
  created_at?: Date | string
  updated_at?: Date | string
  Eventos_Musicas?: Prisma.Eventos_MusicasUncheckedCreateNestedManyWithoutEventos_musicas_evento_id_fkeyInput
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUncheckedCreateNestedManyWithoutEventos_integrantes_evento_id_fkeyInput
}

export type EventosCreateOrConnectWithoutEventos_fk_tipo_evento_fkeyInput = {
  where: Prisma.EventosWhereUniqueInput
  create: Prisma.XOR<Prisma.EventosCreateWithoutEventos_fk_tipo_evento_fkeyInput, Prisma.EventosUncheckedCreateWithoutEventos_fk_tipo_evento_fkeyInput>
}

export type EventosCreateManyEventos_fk_tipo_evento_fkeyInputEnvelope = {
  data: Prisma.EventosCreateManyEventos_fk_tipo_evento_fkeyInput | Prisma.EventosCreateManyEventos_fk_tipo_evento_fkeyInput[]
  skipDuplicates?: boolean
}

export type EventosUpsertWithWhereUniqueWithoutEventos_fk_tipo_evento_fkeyInput = {
  where: Prisma.EventosWhereUniqueInput
  update: Prisma.XOR<Prisma.EventosUpdateWithoutEventos_fk_tipo_evento_fkeyInput, Prisma.EventosUncheckedUpdateWithoutEventos_fk_tipo_evento_fkeyInput>
  create: Prisma.XOR<Prisma.EventosCreateWithoutEventos_fk_tipo_evento_fkeyInput, Prisma.EventosUncheckedCreateWithoutEventos_fk_tipo_evento_fkeyInput>
}

export type EventosUpdateWithWhereUniqueWithoutEventos_fk_tipo_evento_fkeyInput = {
  where: Prisma.EventosWhereUniqueInput
  data: Prisma.XOR<Prisma.EventosUpdateWithoutEventos_fk_tipo_evento_fkeyInput, Prisma.EventosUncheckedUpdateWithoutEventos_fk_tipo_evento_fkeyInput>
}

export type EventosUpdateManyWithWhereWithoutEventos_fk_tipo_evento_fkeyInput = {
  where: Prisma.EventosScalarWhereInput
  data: Prisma.XOR<Prisma.EventosUpdateManyMutationInput, Prisma.EventosUncheckedUpdateManyWithoutEventos_fk_tipo_evento_fkeyInput>
}

export type EventosScalarWhereInput = {
  AND?: Prisma.EventosScalarWhereInput | Prisma.EventosScalarWhereInput[]
  OR?: Prisma.EventosScalarWhereInput[]
  NOT?: Prisma.EventosScalarWhereInput | Prisma.EventosScalarWhereInput[]
  id?: Prisma.UuidFilter<"Eventos"> | string
  data?: Prisma.DateTimeFilter<"Eventos"> | Date | string
  fk_tipo_evento?: Prisma.UuidFilter<"Eventos"> | string
  descricao?: Prisma.StringFilter<"Eventos"> | string
  created_at?: Prisma.DateTimeFilter<"Eventos"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Eventos"> | Date | string
}

export type EventosCreateManyEventos_fk_tipo_evento_fkeyInput = {
  id?: string
  data: Date | string
  descricao: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type EventosUpdateWithoutEventos_fk_tipo_evento_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  descricao?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Eventos_Musicas?: Prisma.Eventos_MusicasUpdateManyWithoutEventos_musicas_evento_id_fkeyNestedInput
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUpdateManyWithoutEventos_integrantes_evento_id_fkeyNestedInput
}

export type EventosUncheckedUpdateWithoutEventos_fk_tipo_evento_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  descricao?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Eventos_Musicas?: Prisma.Eventos_MusicasUncheckedUpdateManyWithoutEventos_musicas_evento_id_fkeyNestedInput
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUncheckedUpdateManyWithoutEventos_integrantes_evento_id_fkeyNestedInput
}

export type EventosUncheckedUpdateManyWithoutEventos_fk_tipo_evento_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  descricao?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type EventosCountOutputType
 */

export type EventosCountOutputType = {
  Eventos_Musicas: number
  Eventos_Integrantes: number
}

export type EventosCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Eventos_Musicas?: boolean | EventosCountOutputTypeCountEventos_MusicasArgs
  Eventos_Integrantes?: boolean | EventosCountOutputTypeCountEventos_IntegrantesArgs
}

/**
 * EventosCountOutputType without action
 */
export type EventosCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventosCountOutputType
   */
  select?: Prisma.EventosCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EventosCountOutputType without action
 */
export type EventosCountOutputTypeCountEventos_MusicasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Eventos_MusicasWhereInput
}

/**
 * EventosCountOutputType without action
 */
export type EventosCountOutputTypeCountEventos_IntegrantesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Eventos_IntegrantesWhereInput
}


export type EventosSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  data?: boolean
  fk_tipo_evento?: boolean
  descricao?: boolean
  created_at?: boolean
  updated_at?: boolean
  eventos_fk_tipo_evento_fkey?: boolean | Prisma.Tipos_EventosDefaultArgs<ExtArgs>
  Eventos_Musicas?: boolean | Prisma.Eventos$Eventos_MusicasArgs<ExtArgs>
  Eventos_Integrantes?: boolean | Prisma.Eventos$Eventos_IntegrantesArgs<ExtArgs>
  _count?: boolean | Prisma.EventosCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventos"]>

export type EventosSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  data?: boolean
  fk_tipo_evento?: boolean
  descricao?: boolean
  created_at?: boolean
  updated_at?: boolean
  eventos_fk_tipo_evento_fkey?: boolean | Prisma.Tipos_EventosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventos"]>

export type EventosSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  data?: boolean
  fk_tipo_evento?: boolean
  descricao?: boolean
  created_at?: boolean
  updated_at?: boolean
  eventos_fk_tipo_evento_fkey?: boolean | Prisma.Tipos_EventosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventos"]>

export type EventosSelectScalar = {
  id?: boolean
  data?: boolean
  fk_tipo_evento?: boolean
  descricao?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type EventosOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "data" | "fk_tipo_evento" | "descricao" | "created_at" | "updated_at", ExtArgs["result"]["eventos"]>
export type EventosInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eventos_fk_tipo_evento_fkey?: boolean | Prisma.Tipos_EventosDefaultArgs<ExtArgs>
  Eventos_Musicas?: boolean | Prisma.Eventos$Eventos_MusicasArgs<ExtArgs>
  Eventos_Integrantes?: boolean | Prisma.Eventos$Eventos_IntegrantesArgs<ExtArgs>
  _count?: boolean | Prisma.EventosCountOutputTypeDefaultArgs<ExtArgs>
}
export type EventosIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eventos_fk_tipo_evento_fkey?: boolean | Prisma.Tipos_EventosDefaultArgs<ExtArgs>
}
export type EventosIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  eventos_fk_tipo_evento_fkey?: boolean | Prisma.Tipos_EventosDefaultArgs<ExtArgs>
}

export type $EventosPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Eventos"
  objects: {
    eventos_fk_tipo_evento_fkey: Prisma.$Tipos_EventosPayload<ExtArgs>
    Eventos_Musicas: Prisma.$Eventos_MusicasPayload<ExtArgs>[]
    Eventos_Integrantes: Prisma.$Eventos_IntegrantesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    data: Date
    fk_tipo_evento: string
    descricao: string
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["eventos"]>
  composites: {}
}

export type EventosGetPayload<S extends boolean | null | undefined | EventosDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventosPayload, S>

export type EventosCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventosFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventosCountAggregateInputType | true
  }

export interface EventosDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Eventos'], meta: { name: 'Eventos' } }
  /**
   * Find zero or one Eventos that matches the filter.
   * @param {EventosFindUniqueArgs} args - Arguments to find a Eventos
   * @example
   * // Get one Eventos
   * const eventos = await prisma.eventos.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventosFindUniqueArgs>(args: Prisma.SelectSubset<T, EventosFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventosClient<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Eventos that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventosFindUniqueOrThrowArgs} args - Arguments to find a Eventos
   * @example
   * // Get one Eventos
   * const eventos = await prisma.eventos.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventosFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventosFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventosClient<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Eventos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventosFindFirstArgs} args - Arguments to find a Eventos
   * @example
   * // Get one Eventos
   * const eventos = await prisma.eventos.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventosFindFirstArgs>(args?: Prisma.SelectSubset<T, EventosFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventosClient<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Eventos that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventosFindFirstOrThrowArgs} args - Arguments to find a Eventos
   * @example
   * // Get one Eventos
   * const eventos = await prisma.eventos.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventosFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventosFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventosClient<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Eventos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventosFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Eventos
   * const eventos = await prisma.eventos.findMany()
   * 
   * // Get first 10 Eventos
   * const eventos = await prisma.eventos.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventosWithIdOnly = await prisma.eventos.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventosFindManyArgs>(args?: Prisma.SelectSubset<T, EventosFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Eventos.
   * @param {EventosCreateArgs} args - Arguments to create a Eventos.
   * @example
   * // Create one Eventos
   * const Eventos = await prisma.eventos.create({
   *   data: {
   *     // ... data to create a Eventos
   *   }
   * })
   * 
   */
  create<T extends EventosCreateArgs>(args: Prisma.SelectSubset<T, EventosCreateArgs<ExtArgs>>): Prisma.Prisma__EventosClient<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Eventos.
   * @param {EventosCreateManyArgs} args - Arguments to create many Eventos.
   * @example
   * // Create many Eventos
   * const eventos = await prisma.eventos.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventosCreateManyArgs>(args?: Prisma.SelectSubset<T, EventosCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Eventos and returns the data saved in the database.
   * @param {EventosCreateManyAndReturnArgs} args - Arguments to create many Eventos.
   * @example
   * // Create many Eventos
   * const eventos = await prisma.eventos.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Eventos and only return the `id`
   * const eventosWithIdOnly = await prisma.eventos.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventosCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventosCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Eventos.
   * @param {EventosDeleteArgs} args - Arguments to delete one Eventos.
   * @example
   * // Delete one Eventos
   * const Eventos = await prisma.eventos.delete({
   *   where: {
   *     // ... filter to delete one Eventos
   *   }
   * })
   * 
   */
  delete<T extends EventosDeleteArgs>(args: Prisma.SelectSubset<T, EventosDeleteArgs<ExtArgs>>): Prisma.Prisma__EventosClient<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Eventos.
   * @param {EventosUpdateArgs} args - Arguments to update one Eventos.
   * @example
   * // Update one Eventos
   * const eventos = await prisma.eventos.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventosUpdateArgs>(args: Prisma.SelectSubset<T, EventosUpdateArgs<ExtArgs>>): Prisma.Prisma__EventosClient<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Eventos.
   * @param {EventosDeleteManyArgs} args - Arguments to filter Eventos to delete.
   * @example
   * // Delete a few Eventos
   * const { count } = await prisma.eventos.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventosDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventosDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Eventos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventosUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Eventos
   * const eventos = await prisma.eventos.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventosUpdateManyArgs>(args: Prisma.SelectSubset<T, EventosUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Eventos and returns the data updated in the database.
   * @param {EventosUpdateManyAndReturnArgs} args - Arguments to update many Eventos.
   * @example
   * // Update many Eventos
   * const eventos = await prisma.eventos.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Eventos and only return the `id`
   * const eventosWithIdOnly = await prisma.eventos.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventosUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventosUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Eventos.
   * @param {EventosUpsertArgs} args - Arguments to update or create a Eventos.
   * @example
   * // Update or create a Eventos
   * const eventos = await prisma.eventos.upsert({
   *   create: {
   *     // ... data to create a Eventos
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Eventos we want to update
   *   }
   * })
   */
  upsert<T extends EventosUpsertArgs>(args: Prisma.SelectSubset<T, EventosUpsertArgs<ExtArgs>>): Prisma.Prisma__EventosClient<runtime.Types.Result.GetResult<Prisma.$EventosPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Eventos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventosCountArgs} args - Arguments to filter Eventos to count.
   * @example
   * // Count the number of Eventos
   * const count = await prisma.eventos.count({
   *   where: {
   *     // ... the filter for the Eventos we want to count
   *   }
   * })
  **/
  count<T extends EventosCountArgs>(
    args?: Prisma.Subset<T, EventosCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventosCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Eventos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventosAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventosAggregateArgs>(args: Prisma.Subset<T, EventosAggregateArgs>): Prisma.PrismaPromise<GetEventosAggregateType<T>>

  /**
   * Group by Eventos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventosGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventosGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventosGroupByArgs['orderBy'] }
      : { orderBy?: EventosGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventosGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventosGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Eventos model
 */
readonly fields: EventosFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Eventos.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventosClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  eventos_fk_tipo_evento_fkey<T extends Prisma.Tipos_EventosDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tipos_EventosDefaultArgs<ExtArgs>>): Prisma.Prisma__Tipos_EventosClient<runtime.Types.Result.GetResult<Prisma.$Tipos_EventosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Eventos_Musicas<T extends Prisma.Eventos$Eventos_MusicasArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Eventos$Eventos_MusicasArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Eventos_MusicasPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Eventos_Integrantes<T extends Prisma.Eventos$Eventos_IntegrantesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Eventos$Eventos_IntegrantesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Eventos model
 */
export interface EventosFieldRefs {
  readonly id: Prisma.FieldRef<"Eventos", 'String'>
  readonly data: Prisma.FieldRef<"Eventos", 'DateTime'>
  readonly fk_tipo_evento: Prisma.FieldRef<"Eventos", 'String'>
  readonly descricao: Prisma.FieldRef<"Eventos", 'String'>
  readonly created_at: Prisma.FieldRef<"Eventos", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Eventos", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Eventos findUnique
 */
export type EventosFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosInclude<ExtArgs> | null
  /**
   * Filter, which Eventos to fetch.
   */
  where: Prisma.EventosWhereUniqueInput
}

/**
 * Eventos findUniqueOrThrow
 */
export type EventosFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosInclude<ExtArgs> | null
  /**
   * Filter, which Eventos to fetch.
   */
  where: Prisma.EventosWhereUniqueInput
}

/**
 * Eventos findFirst
 */
export type EventosFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosInclude<ExtArgs> | null
  /**
   * Filter, which Eventos to fetch.
   */
  where?: Prisma.EventosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Eventos to fetch.
   */
  orderBy?: Prisma.EventosOrderByWithRelationInput | Prisma.EventosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Eventos.
   */
  cursor?: Prisma.EventosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Eventos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Eventos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Eventos.
   */
  distinct?: Prisma.EventosScalarFieldEnum | Prisma.EventosScalarFieldEnum[]
}

/**
 * Eventos findFirstOrThrow
 */
export type EventosFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosInclude<ExtArgs> | null
  /**
   * Filter, which Eventos to fetch.
   */
  where?: Prisma.EventosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Eventos to fetch.
   */
  orderBy?: Prisma.EventosOrderByWithRelationInput | Prisma.EventosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Eventos.
   */
  cursor?: Prisma.EventosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Eventos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Eventos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Eventos.
   */
  distinct?: Prisma.EventosScalarFieldEnum | Prisma.EventosScalarFieldEnum[]
}

/**
 * Eventos findMany
 */
export type EventosFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosInclude<ExtArgs> | null
  /**
   * Filter, which Eventos to fetch.
   */
  where?: Prisma.EventosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Eventos to fetch.
   */
  orderBy?: Prisma.EventosOrderByWithRelationInput | Prisma.EventosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Eventos.
   */
  cursor?: Prisma.EventosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Eventos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Eventos.
   */
  skip?: number
  distinct?: Prisma.EventosScalarFieldEnum | Prisma.EventosScalarFieldEnum[]
}

/**
 * Eventos create
 */
export type EventosCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosInclude<ExtArgs> | null
  /**
   * The data needed to create a Eventos.
   */
  data: Prisma.XOR<Prisma.EventosCreateInput, Prisma.EventosUncheckedCreateInput>
}

/**
 * Eventos createMany
 */
export type EventosCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Eventos.
   */
  data: Prisma.EventosCreateManyInput | Prisma.EventosCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Eventos createManyAndReturn
 */
export type EventosCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * The data used to create many Eventos.
   */
  data: Prisma.EventosCreateManyInput | Prisma.EventosCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Eventos update
 */
export type EventosUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosInclude<ExtArgs> | null
  /**
   * The data needed to update a Eventos.
   */
  data: Prisma.XOR<Prisma.EventosUpdateInput, Prisma.EventosUncheckedUpdateInput>
  /**
   * Choose, which Eventos to update.
   */
  where: Prisma.EventosWhereUniqueInput
}

/**
 * Eventos updateMany
 */
export type EventosUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Eventos.
   */
  data: Prisma.XOR<Prisma.EventosUpdateManyMutationInput, Prisma.EventosUncheckedUpdateManyInput>
  /**
   * Filter which Eventos to update
   */
  where?: Prisma.EventosWhereInput
  /**
   * Limit how many Eventos to update.
   */
  limit?: number
}

/**
 * Eventos updateManyAndReturn
 */
export type EventosUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * The data used to update Eventos.
   */
  data: Prisma.XOR<Prisma.EventosUpdateManyMutationInput, Prisma.EventosUncheckedUpdateManyInput>
  /**
   * Filter which Eventos to update
   */
  where?: Prisma.EventosWhereInput
  /**
   * Limit how many Eventos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Eventos upsert
 */
export type EventosUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosInclude<ExtArgs> | null
  /**
   * The filter to search for the Eventos to update in case it exists.
   */
  where: Prisma.EventosWhereUniqueInput
  /**
   * In case the Eventos found by the `where` argument doesn't exist, create a new Eventos with this data.
   */
  create: Prisma.XOR<Prisma.EventosCreateInput, Prisma.EventosUncheckedCreateInput>
  /**
   * In case the Eventos was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventosUpdateInput, Prisma.EventosUncheckedUpdateInput>
}

/**
 * Eventos delete
 */
export type EventosDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosInclude<ExtArgs> | null
  /**
   * Filter which Eventos to delete.
   */
  where: Prisma.EventosWhereUniqueInput
}

/**
 * Eventos deleteMany
 */
export type EventosDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Eventos to delete
   */
  where?: Prisma.EventosWhereInput
  /**
   * Limit how many Eventos to delete.
   */
  limit?: number
}

/**
 * Eventos.Eventos_Musicas
 */
export type Eventos$Eventos_MusicasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Musicas
   */
  select?: Prisma.Eventos_MusicasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Musicas
   */
  omit?: Prisma.Eventos_MusicasOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_MusicasInclude<ExtArgs> | null
  where?: Prisma.Eventos_MusicasWhereInput
  orderBy?: Prisma.Eventos_MusicasOrderByWithRelationInput | Prisma.Eventos_MusicasOrderByWithRelationInput[]
  cursor?: Prisma.Eventos_MusicasWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Eventos_MusicasScalarFieldEnum | Prisma.Eventos_MusicasScalarFieldEnum[]
}

/**
 * Eventos.Eventos_Integrantes
 */
export type Eventos$Eventos_IntegrantesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
  where?: Prisma.Eventos_IntegrantesWhereInput
  orderBy?: Prisma.Eventos_IntegrantesOrderByWithRelationInput | Prisma.Eventos_IntegrantesOrderByWithRelationInput[]
  cursor?: Prisma.Eventos_IntegrantesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Eventos_IntegrantesScalarFieldEnum | Prisma.Eventos_IntegrantesScalarFieldEnum[]
}

/**
 * Eventos without action
 */
export type EventosDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos
   */
  select?: Prisma.EventosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos
   */
  omit?: Prisma.EventosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventosInclude<ExtArgs> | null
}
