
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Integrantes` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Integrantes
 * 
 */
export type IntegrantesModel = runtime.Types.Result.DefaultSelection<Prisma.$IntegrantesPayload>

export type AggregateIntegrantes = {
  _count: IntegrantesCountAggregateOutputType | null
  _min: IntegrantesMinAggregateOutputType | null
  _max: IntegrantesMaxAggregateOutputType | null
}

export type IntegrantesMinAggregateOutputType = {
  id: string | null
  nome: string | null
  doc_id: string | null
  email: string | null
  senha: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type IntegrantesMaxAggregateOutputType = {
  id: string | null
  nome: string | null
  doc_id: string | null
  email: string | null
  senha: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type IntegrantesCountAggregateOutputType = {
  id: number
  nome: number
  doc_id: number
  email: number
  senha: number
  created_at: number
  updated_at: number
  _all: number
}


export type IntegrantesMinAggregateInputType = {
  id?: true
  nome?: true
  doc_id?: true
  email?: true
  senha?: true
  created_at?: true
  updated_at?: true
}

export type IntegrantesMaxAggregateInputType = {
  id?: true
  nome?: true
  doc_id?: true
  email?: true
  senha?: true
  created_at?: true
  updated_at?: true
}

export type IntegrantesCountAggregateInputType = {
  id?: true
  nome?: true
  doc_id?: true
  email?: true
  senha?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type IntegrantesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Integrantes to aggregate.
   */
  where?: Prisma.IntegrantesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Integrantes to fetch.
   */
  orderBy?: Prisma.IntegrantesOrderByWithRelationInput | Prisma.IntegrantesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.IntegrantesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Integrantes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Integrantes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Integrantes
  **/
  _count?: true | IntegrantesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: IntegrantesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: IntegrantesMaxAggregateInputType
}

export type GetIntegrantesAggregateType<T extends IntegrantesAggregateArgs> = {
      [P in keyof T & keyof AggregateIntegrantes]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIntegrantes[P]>
    : Prisma.GetScalarType<T[P], AggregateIntegrantes[P]>
}




export type IntegrantesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IntegrantesWhereInput
  orderBy?: Prisma.IntegrantesOrderByWithAggregationInput | Prisma.IntegrantesOrderByWithAggregationInput[]
  by: Prisma.IntegrantesScalarFieldEnum[] | Prisma.IntegrantesScalarFieldEnum
  having?: Prisma.IntegrantesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: IntegrantesCountAggregateInputType | true
  _min?: IntegrantesMinAggregateInputType
  _max?: IntegrantesMaxAggregateInputType
}

export type IntegrantesGroupByOutputType = {
  id: string
  nome: string
  doc_id: string
  email: string
  senha: string
  created_at: Date
  updated_at: Date
  _count: IntegrantesCountAggregateOutputType | null
  _min: IntegrantesMinAggregateOutputType | null
  _max: IntegrantesMaxAggregateOutputType | null
}

type GetIntegrantesGroupByPayload<T extends IntegrantesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<IntegrantesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof IntegrantesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], IntegrantesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], IntegrantesGroupByOutputType[P]>
      }
    >
  >



export type IntegrantesWhereInput = {
  AND?: Prisma.IntegrantesWhereInput | Prisma.IntegrantesWhereInput[]
  OR?: Prisma.IntegrantesWhereInput[]
  NOT?: Prisma.IntegrantesWhereInput | Prisma.IntegrantesWhereInput[]
  id?: Prisma.UuidFilter<"Integrantes"> | string
  nome?: Prisma.StringFilter<"Integrantes"> | string
  doc_id?: Prisma.StringFilter<"Integrantes"> | string
  email?: Prisma.StringFilter<"Integrantes"> | string
  senha?: Prisma.StringFilter<"Integrantes"> | string
  created_at?: Prisma.DateTimeFilter<"Integrantes"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Integrantes"> | Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesListRelationFilter
  Integrantes_Funcoes?: Prisma.Integrantes_FuncoesListRelationFilter
}

export type IntegrantesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  doc_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesOrderByRelationAggregateInput
  Integrantes_Funcoes?: Prisma.Integrantes_FuncoesOrderByRelationAggregateInput
}

export type IntegrantesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  doc_id?: string
  email?: string
  AND?: Prisma.IntegrantesWhereInput | Prisma.IntegrantesWhereInput[]
  OR?: Prisma.IntegrantesWhereInput[]
  NOT?: Prisma.IntegrantesWhereInput | Prisma.IntegrantesWhereInput[]
  nome?: Prisma.StringFilter<"Integrantes"> | string
  senha?: Prisma.StringFilter<"Integrantes"> | string
  created_at?: Prisma.DateTimeFilter<"Integrantes"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Integrantes"> | Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesListRelationFilter
  Integrantes_Funcoes?: Prisma.Integrantes_FuncoesListRelationFilter
}, "id" | "doc_id" | "email">

export type IntegrantesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  doc_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.IntegrantesCountOrderByAggregateInput
  _max?: Prisma.IntegrantesMaxOrderByAggregateInput
  _min?: Prisma.IntegrantesMinOrderByAggregateInput
}

export type IntegrantesScalarWhereWithAggregatesInput = {
  AND?: Prisma.IntegrantesScalarWhereWithAggregatesInput | Prisma.IntegrantesScalarWhereWithAggregatesInput[]
  OR?: Prisma.IntegrantesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.IntegrantesScalarWhereWithAggregatesInput | Prisma.IntegrantesScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Integrantes"> | string
  nome?: Prisma.StringWithAggregatesFilter<"Integrantes"> | string
  doc_id?: Prisma.StringWithAggregatesFilter<"Integrantes"> | string
  email?: Prisma.StringWithAggregatesFilter<"Integrantes"> | string
  senha?: Prisma.StringWithAggregatesFilter<"Integrantes"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Integrantes"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Integrantes"> | Date | string
}

export type IntegrantesCreateInput = {
  id?: string
  nome: string
  doc_id: string
  email: string
  senha: string
  created_at?: Date | string
  updated_at?: Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesCreateNestedManyWithoutEventos_integrantes_musico_id_fkeyInput
  Integrantes_Funcoes?: Prisma.Integrantes_FuncoesCreateNestedManyWithoutIntegrantes_funcoes_musico_id_fkeyInput
}

export type IntegrantesUncheckedCreateInput = {
  id?: string
  nome: string
  doc_id: string
  email: string
  senha: string
  created_at?: Date | string
  updated_at?: Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUncheckedCreateNestedManyWithoutEventos_integrantes_musico_id_fkeyInput
  Integrantes_Funcoes?: Prisma.Integrantes_FuncoesUncheckedCreateNestedManyWithoutIntegrantes_funcoes_musico_id_fkeyInput
}

export type IntegrantesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  doc_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUpdateManyWithoutEventos_integrantes_musico_id_fkeyNestedInput
  Integrantes_Funcoes?: Prisma.Integrantes_FuncoesUpdateManyWithoutIntegrantes_funcoes_musico_id_fkeyNestedInput
}

export type IntegrantesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  doc_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUncheckedUpdateManyWithoutEventos_integrantes_musico_id_fkeyNestedInput
  Integrantes_Funcoes?: Prisma.Integrantes_FuncoesUncheckedUpdateManyWithoutIntegrantes_funcoes_musico_id_fkeyNestedInput
}

export type IntegrantesCreateManyInput = {
  id?: string
  nome: string
  doc_id: string
  email: string
  senha: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type IntegrantesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  doc_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IntegrantesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  doc_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IntegrantesScalarRelationFilter = {
  is?: Prisma.IntegrantesWhereInput
  isNot?: Prisma.IntegrantesWhereInput
}

export type IntegrantesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  doc_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type IntegrantesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  doc_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type IntegrantesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  doc_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type IntegrantesCreateNestedOneWithoutEventos_IntegrantesInput = {
  create?: Prisma.XOR<Prisma.IntegrantesCreateWithoutEventos_IntegrantesInput, Prisma.IntegrantesUncheckedCreateWithoutEventos_IntegrantesInput>
  connectOrCreate?: Prisma.IntegrantesCreateOrConnectWithoutEventos_IntegrantesInput
  connect?: Prisma.IntegrantesWhereUniqueInput
}

export type IntegrantesUpdateOneRequiredWithoutEventos_IntegrantesNestedInput = {
  create?: Prisma.XOR<Prisma.IntegrantesCreateWithoutEventos_IntegrantesInput, Prisma.IntegrantesUncheckedCreateWithoutEventos_IntegrantesInput>
  connectOrCreate?: Prisma.IntegrantesCreateOrConnectWithoutEventos_IntegrantesInput
  upsert?: Prisma.IntegrantesUpsertWithoutEventos_IntegrantesInput
  connect?: Prisma.IntegrantesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.IntegrantesUpdateToOneWithWhereWithoutEventos_IntegrantesInput, Prisma.IntegrantesUpdateWithoutEventos_IntegrantesInput>, Prisma.IntegrantesUncheckedUpdateWithoutEventos_IntegrantesInput>
}

export type IntegrantesCreateNestedOneWithoutIntegrantes_FuncoesInput = {
  create?: Prisma.XOR<Prisma.IntegrantesCreateWithoutIntegrantes_FuncoesInput, Prisma.IntegrantesUncheckedCreateWithoutIntegrantes_FuncoesInput>
  connectOrCreate?: Prisma.IntegrantesCreateOrConnectWithoutIntegrantes_FuncoesInput
  connect?: Prisma.IntegrantesWhereUniqueInput
}

export type IntegrantesUpdateOneRequiredWithoutIntegrantes_FuncoesNestedInput = {
  create?: Prisma.XOR<Prisma.IntegrantesCreateWithoutIntegrantes_FuncoesInput, Prisma.IntegrantesUncheckedCreateWithoutIntegrantes_FuncoesInput>
  connectOrCreate?: Prisma.IntegrantesCreateOrConnectWithoutIntegrantes_FuncoesInput
  upsert?: Prisma.IntegrantesUpsertWithoutIntegrantes_FuncoesInput
  connect?: Prisma.IntegrantesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.IntegrantesUpdateToOneWithWhereWithoutIntegrantes_FuncoesInput, Prisma.IntegrantesUpdateWithoutIntegrantes_FuncoesInput>, Prisma.IntegrantesUncheckedUpdateWithoutIntegrantes_FuncoesInput>
}

export type IntegrantesCreateWithoutEventos_IntegrantesInput = {
  id?: string
  nome: string
  doc_id: string
  email: string
  senha: string
  created_at?: Date | string
  updated_at?: Date | string
  Integrantes_Funcoes?: Prisma.Integrantes_FuncoesCreateNestedManyWithoutIntegrantes_funcoes_musico_id_fkeyInput
}

export type IntegrantesUncheckedCreateWithoutEventos_IntegrantesInput = {
  id?: string
  nome: string
  doc_id: string
  email: string
  senha: string
  created_at?: Date | string
  updated_at?: Date | string
  Integrantes_Funcoes?: Prisma.Integrantes_FuncoesUncheckedCreateNestedManyWithoutIntegrantes_funcoes_musico_id_fkeyInput
}

export type IntegrantesCreateOrConnectWithoutEventos_IntegrantesInput = {
  where: Prisma.IntegrantesWhereUniqueInput
  create: Prisma.XOR<Prisma.IntegrantesCreateWithoutEventos_IntegrantesInput, Prisma.IntegrantesUncheckedCreateWithoutEventos_IntegrantesInput>
}

export type IntegrantesUpsertWithoutEventos_IntegrantesInput = {
  update: Prisma.XOR<Prisma.IntegrantesUpdateWithoutEventos_IntegrantesInput, Prisma.IntegrantesUncheckedUpdateWithoutEventos_IntegrantesInput>
  create: Prisma.XOR<Prisma.IntegrantesCreateWithoutEventos_IntegrantesInput, Prisma.IntegrantesUncheckedCreateWithoutEventos_IntegrantesInput>
  where?: Prisma.IntegrantesWhereInput
}

export type IntegrantesUpdateToOneWithWhereWithoutEventos_IntegrantesInput = {
  where?: Prisma.IntegrantesWhereInput
  data: Prisma.XOR<Prisma.IntegrantesUpdateWithoutEventos_IntegrantesInput, Prisma.IntegrantesUncheckedUpdateWithoutEventos_IntegrantesInput>
}

export type IntegrantesUpdateWithoutEventos_IntegrantesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  doc_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Integrantes_Funcoes?: Prisma.Integrantes_FuncoesUpdateManyWithoutIntegrantes_funcoes_musico_id_fkeyNestedInput
}

export type IntegrantesUncheckedUpdateWithoutEventos_IntegrantesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  doc_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Integrantes_Funcoes?: Prisma.Integrantes_FuncoesUncheckedUpdateManyWithoutIntegrantes_funcoes_musico_id_fkeyNestedInput
}

export type IntegrantesCreateWithoutIntegrantes_FuncoesInput = {
  id?: string
  nome: string
  doc_id: string
  email: string
  senha: string
  created_at?: Date | string
  updated_at?: Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesCreateNestedManyWithoutEventos_integrantes_musico_id_fkeyInput
}

export type IntegrantesUncheckedCreateWithoutIntegrantes_FuncoesInput = {
  id?: string
  nome: string
  doc_id: string
  email: string
  senha: string
  created_at?: Date | string
  updated_at?: Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUncheckedCreateNestedManyWithoutEventos_integrantes_musico_id_fkeyInput
}

export type IntegrantesCreateOrConnectWithoutIntegrantes_FuncoesInput = {
  where: Prisma.IntegrantesWhereUniqueInput
  create: Prisma.XOR<Prisma.IntegrantesCreateWithoutIntegrantes_FuncoesInput, Prisma.IntegrantesUncheckedCreateWithoutIntegrantes_FuncoesInput>
}

export type IntegrantesUpsertWithoutIntegrantes_FuncoesInput = {
  update: Prisma.XOR<Prisma.IntegrantesUpdateWithoutIntegrantes_FuncoesInput, Prisma.IntegrantesUncheckedUpdateWithoutIntegrantes_FuncoesInput>
  create: Prisma.XOR<Prisma.IntegrantesCreateWithoutIntegrantes_FuncoesInput, Prisma.IntegrantesUncheckedCreateWithoutIntegrantes_FuncoesInput>
  where?: Prisma.IntegrantesWhereInput
}

export type IntegrantesUpdateToOneWithWhereWithoutIntegrantes_FuncoesInput = {
  where?: Prisma.IntegrantesWhereInput
  data: Prisma.XOR<Prisma.IntegrantesUpdateWithoutIntegrantes_FuncoesInput, Prisma.IntegrantesUncheckedUpdateWithoutIntegrantes_FuncoesInput>
}

export type IntegrantesUpdateWithoutIntegrantes_FuncoesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  doc_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUpdateManyWithoutEventos_integrantes_musico_id_fkeyNestedInput
}

export type IntegrantesUncheckedUpdateWithoutIntegrantes_FuncoesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  doc_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Eventos_Integrantes?: Prisma.Eventos_IntegrantesUncheckedUpdateManyWithoutEventos_integrantes_musico_id_fkeyNestedInput
}


/**
 * Count Type IntegrantesCountOutputType
 */

export type IntegrantesCountOutputType = {
  Eventos_Integrantes: number
  Integrantes_Funcoes: number
}

export type IntegrantesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Eventos_Integrantes?: boolean | IntegrantesCountOutputTypeCountEventos_IntegrantesArgs
  Integrantes_Funcoes?: boolean | IntegrantesCountOutputTypeCountIntegrantes_FuncoesArgs
}

/**
 * IntegrantesCountOutputType without action
 */
export type IntegrantesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IntegrantesCountOutputType
   */
  select?: Prisma.IntegrantesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * IntegrantesCountOutputType without action
 */
export type IntegrantesCountOutputTypeCountEventos_IntegrantesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Eventos_IntegrantesWhereInput
}

/**
 * IntegrantesCountOutputType without action
 */
export type IntegrantesCountOutputTypeCountIntegrantes_FuncoesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Integrantes_FuncoesWhereInput
}


export type IntegrantesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  doc_id?: boolean
  email?: boolean
  senha?: boolean
  created_at?: boolean
  updated_at?: boolean
  Eventos_Integrantes?: boolean | Prisma.Integrantes$Eventos_IntegrantesArgs<ExtArgs>
  Integrantes_Funcoes?: boolean | Prisma.Integrantes$Integrantes_FuncoesArgs<ExtArgs>
  _count?: boolean | Prisma.IntegrantesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["integrantes"]>

export type IntegrantesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  doc_id?: boolean
  email?: boolean
  senha?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["integrantes"]>

export type IntegrantesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  doc_id?: boolean
  email?: boolean
  senha?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["integrantes"]>

export type IntegrantesSelectScalar = {
  id?: boolean
  nome?: boolean
  doc_id?: boolean
  email?: boolean
  senha?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type IntegrantesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nome" | "doc_id" | "email" | "senha" | "created_at" | "updated_at", ExtArgs["result"]["integrantes"]>
export type IntegrantesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Eventos_Integrantes?: boolean | Prisma.Integrantes$Eventos_IntegrantesArgs<ExtArgs>
  Integrantes_Funcoes?: boolean | Prisma.Integrantes$Integrantes_FuncoesArgs<ExtArgs>
  _count?: boolean | Prisma.IntegrantesCountOutputTypeDefaultArgs<ExtArgs>
}
export type IntegrantesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type IntegrantesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $IntegrantesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Integrantes"
  objects: {
    Eventos_Integrantes: Prisma.$Eventos_IntegrantesPayload<ExtArgs>[]
    Integrantes_Funcoes: Prisma.$Integrantes_FuncoesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    nome: string
    doc_id: string
    email: string
    senha: string
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["integrantes"]>
  composites: {}
}

export type IntegrantesGetPayload<S extends boolean | null | undefined | IntegrantesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload, S>

export type IntegrantesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<IntegrantesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: IntegrantesCountAggregateInputType | true
  }

export interface IntegrantesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Integrantes'], meta: { name: 'Integrantes' } }
  /**
   * Find zero or one Integrantes that matches the filter.
   * @param {IntegrantesFindUniqueArgs} args - Arguments to find a Integrantes
   * @example
   * // Get one Integrantes
   * const integrantes = await prisma.integrantes.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends IntegrantesFindUniqueArgs>(args: Prisma.SelectSubset<T, IntegrantesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Integrantes that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {IntegrantesFindUniqueOrThrowArgs} args - Arguments to find a Integrantes
   * @example
   * // Get one Integrantes
   * const integrantes = await prisma.integrantes.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends IntegrantesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, IntegrantesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Integrantes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IntegrantesFindFirstArgs} args - Arguments to find a Integrantes
   * @example
   * // Get one Integrantes
   * const integrantes = await prisma.integrantes.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends IntegrantesFindFirstArgs>(args?: Prisma.SelectSubset<T, IntegrantesFindFirstArgs<ExtArgs>>): Prisma.Prisma__IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Integrantes that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IntegrantesFindFirstOrThrowArgs} args - Arguments to find a Integrantes
   * @example
   * // Get one Integrantes
   * const integrantes = await prisma.integrantes.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends IntegrantesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, IntegrantesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Integrantes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IntegrantesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Integrantes
   * const integrantes = await prisma.integrantes.findMany()
   * 
   * // Get first 10 Integrantes
   * const integrantes = await prisma.integrantes.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const integrantesWithIdOnly = await prisma.integrantes.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends IntegrantesFindManyArgs>(args?: Prisma.SelectSubset<T, IntegrantesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Integrantes.
   * @param {IntegrantesCreateArgs} args - Arguments to create a Integrantes.
   * @example
   * // Create one Integrantes
   * const Integrantes = await prisma.integrantes.create({
   *   data: {
   *     // ... data to create a Integrantes
   *   }
   * })
   * 
   */
  create<T extends IntegrantesCreateArgs>(args: Prisma.SelectSubset<T, IntegrantesCreateArgs<ExtArgs>>): Prisma.Prisma__IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Integrantes.
   * @param {IntegrantesCreateManyArgs} args - Arguments to create many Integrantes.
   * @example
   * // Create many Integrantes
   * const integrantes = await prisma.integrantes.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends IntegrantesCreateManyArgs>(args?: Prisma.SelectSubset<T, IntegrantesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Integrantes and returns the data saved in the database.
   * @param {IntegrantesCreateManyAndReturnArgs} args - Arguments to create many Integrantes.
   * @example
   * // Create many Integrantes
   * const integrantes = await prisma.integrantes.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Integrantes and only return the `id`
   * const integrantesWithIdOnly = await prisma.integrantes.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends IntegrantesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, IntegrantesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Integrantes.
   * @param {IntegrantesDeleteArgs} args - Arguments to delete one Integrantes.
   * @example
   * // Delete one Integrantes
   * const Integrantes = await prisma.integrantes.delete({
   *   where: {
   *     // ... filter to delete one Integrantes
   *   }
   * })
   * 
   */
  delete<T extends IntegrantesDeleteArgs>(args: Prisma.SelectSubset<T, IntegrantesDeleteArgs<ExtArgs>>): Prisma.Prisma__IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Integrantes.
   * @param {IntegrantesUpdateArgs} args - Arguments to update one Integrantes.
   * @example
   * // Update one Integrantes
   * const integrantes = await prisma.integrantes.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends IntegrantesUpdateArgs>(args: Prisma.SelectSubset<T, IntegrantesUpdateArgs<ExtArgs>>): Prisma.Prisma__IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Integrantes.
   * @param {IntegrantesDeleteManyArgs} args - Arguments to filter Integrantes to delete.
   * @example
   * // Delete a few Integrantes
   * const { count } = await prisma.integrantes.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends IntegrantesDeleteManyArgs>(args?: Prisma.SelectSubset<T, IntegrantesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Integrantes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IntegrantesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Integrantes
   * const integrantes = await prisma.integrantes.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends IntegrantesUpdateManyArgs>(args: Prisma.SelectSubset<T, IntegrantesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Integrantes and returns the data updated in the database.
   * @param {IntegrantesUpdateManyAndReturnArgs} args - Arguments to update many Integrantes.
   * @example
   * // Update many Integrantes
   * const integrantes = await prisma.integrantes.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Integrantes and only return the `id`
   * const integrantesWithIdOnly = await prisma.integrantes.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends IntegrantesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, IntegrantesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Integrantes.
   * @param {IntegrantesUpsertArgs} args - Arguments to update or create a Integrantes.
   * @example
   * // Update or create a Integrantes
   * const integrantes = await prisma.integrantes.upsert({
   *   create: {
   *     // ... data to create a Integrantes
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Integrantes we want to update
   *   }
   * })
   */
  upsert<T extends IntegrantesUpsertArgs>(args: Prisma.SelectSubset<T, IntegrantesUpsertArgs<ExtArgs>>): Prisma.Prisma__IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Integrantes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IntegrantesCountArgs} args - Arguments to filter Integrantes to count.
   * @example
   * // Count the number of Integrantes
   * const count = await prisma.integrantes.count({
   *   where: {
   *     // ... the filter for the Integrantes we want to count
   *   }
   * })
  **/
  count<T extends IntegrantesCountArgs>(
    args?: Prisma.Subset<T, IntegrantesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], IntegrantesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Integrantes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IntegrantesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends IntegrantesAggregateArgs>(args: Prisma.Subset<T, IntegrantesAggregateArgs>): Prisma.PrismaPromise<GetIntegrantesAggregateType<T>>

  /**
   * Group by Integrantes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IntegrantesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends IntegrantesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: IntegrantesGroupByArgs['orderBy'] }
      : { orderBy?: IntegrantesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, IntegrantesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIntegrantesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Integrantes model
 */
readonly fields: IntegrantesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Integrantes.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__IntegrantesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Eventos_Integrantes<T extends Prisma.Integrantes$Eventos_IntegrantesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Integrantes$Eventos_IntegrantesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Eventos_IntegrantesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Integrantes_Funcoes<T extends Prisma.Integrantes$Integrantes_FuncoesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Integrantes$Integrantes_FuncoesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Integrantes model
 */
export interface IntegrantesFieldRefs {
  readonly id: Prisma.FieldRef<"Integrantes", 'String'>
  readonly nome: Prisma.FieldRef<"Integrantes", 'String'>
  readonly doc_id: Prisma.FieldRef<"Integrantes", 'String'>
  readonly email: Prisma.FieldRef<"Integrantes", 'String'>
  readonly senha: Prisma.FieldRef<"Integrantes", 'String'>
  readonly created_at: Prisma.FieldRef<"Integrantes", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Integrantes", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Integrantes findUnique
 */
export type IntegrantesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IntegrantesInclude<ExtArgs> | null
  /**
   * Filter, which Integrantes to fetch.
   */
  where: Prisma.IntegrantesWhereUniqueInput
}

/**
 * Integrantes findUniqueOrThrow
 */
export type IntegrantesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IntegrantesInclude<ExtArgs> | null
  /**
   * Filter, which Integrantes to fetch.
   */
  where: Prisma.IntegrantesWhereUniqueInput
}

/**
 * Integrantes findFirst
 */
export type IntegrantesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IntegrantesInclude<ExtArgs> | null
  /**
   * Filter, which Integrantes to fetch.
   */
  where?: Prisma.IntegrantesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Integrantes to fetch.
   */
  orderBy?: Prisma.IntegrantesOrderByWithRelationInput | Prisma.IntegrantesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Integrantes.
   */
  cursor?: Prisma.IntegrantesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Integrantes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Integrantes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Integrantes.
   */
  distinct?: Prisma.IntegrantesScalarFieldEnum | Prisma.IntegrantesScalarFieldEnum[]
}

/**
 * Integrantes findFirstOrThrow
 */
export type IntegrantesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IntegrantesInclude<ExtArgs> | null
  /**
   * Filter, which Integrantes to fetch.
   */
  where?: Prisma.IntegrantesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Integrantes to fetch.
   */
  orderBy?: Prisma.IntegrantesOrderByWithRelationInput | Prisma.IntegrantesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Integrantes.
   */
  cursor?: Prisma.IntegrantesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Integrantes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Integrantes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Integrantes.
   */
  distinct?: Prisma.IntegrantesScalarFieldEnum | Prisma.IntegrantesScalarFieldEnum[]
}

/**
 * Integrantes findMany
 */
export type IntegrantesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IntegrantesInclude<ExtArgs> | null
  /**
   * Filter, which Integrantes to fetch.
   */
  where?: Prisma.IntegrantesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Integrantes to fetch.
   */
  orderBy?: Prisma.IntegrantesOrderByWithRelationInput | Prisma.IntegrantesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Integrantes.
   */
  cursor?: Prisma.IntegrantesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Integrantes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Integrantes.
   */
  skip?: number
  distinct?: Prisma.IntegrantesScalarFieldEnum | Prisma.IntegrantesScalarFieldEnum[]
}

/**
 * Integrantes create
 */
export type IntegrantesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IntegrantesInclude<ExtArgs> | null
  /**
   * The data needed to create a Integrantes.
   */
  data: Prisma.XOR<Prisma.IntegrantesCreateInput, Prisma.IntegrantesUncheckedCreateInput>
}

/**
 * Integrantes createMany
 */
export type IntegrantesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Integrantes.
   */
  data: Prisma.IntegrantesCreateManyInput | Prisma.IntegrantesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Integrantes createManyAndReturn
 */
export type IntegrantesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * The data used to create many Integrantes.
   */
  data: Prisma.IntegrantesCreateManyInput | Prisma.IntegrantesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Integrantes update
 */
export type IntegrantesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IntegrantesInclude<ExtArgs> | null
  /**
   * The data needed to update a Integrantes.
   */
  data: Prisma.XOR<Prisma.IntegrantesUpdateInput, Prisma.IntegrantesUncheckedUpdateInput>
  /**
   * Choose, which Integrantes to update.
   */
  where: Prisma.IntegrantesWhereUniqueInput
}

/**
 * Integrantes updateMany
 */
export type IntegrantesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Integrantes.
   */
  data: Prisma.XOR<Prisma.IntegrantesUpdateManyMutationInput, Prisma.IntegrantesUncheckedUpdateManyInput>
  /**
   * Filter which Integrantes to update
   */
  where?: Prisma.IntegrantesWhereInput
  /**
   * Limit how many Integrantes to update.
   */
  limit?: number
}

/**
 * Integrantes updateManyAndReturn
 */
export type IntegrantesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * The data used to update Integrantes.
   */
  data: Prisma.XOR<Prisma.IntegrantesUpdateManyMutationInput, Prisma.IntegrantesUncheckedUpdateManyInput>
  /**
   * Filter which Integrantes to update
   */
  where?: Prisma.IntegrantesWhereInput
  /**
   * Limit how many Integrantes to update.
   */
  limit?: number
}

/**
 * Integrantes upsert
 */
export type IntegrantesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IntegrantesInclude<ExtArgs> | null
  /**
   * The filter to search for the Integrantes to update in case it exists.
   */
  where: Prisma.IntegrantesWhereUniqueInput
  /**
   * In case the Integrantes found by the `where` argument doesn't exist, create a new Integrantes with this data.
   */
  create: Prisma.XOR<Prisma.IntegrantesCreateInput, Prisma.IntegrantesUncheckedCreateInput>
  /**
   * In case the Integrantes was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.IntegrantesUpdateInput, Prisma.IntegrantesUncheckedUpdateInput>
}

/**
 * Integrantes delete
 */
export type IntegrantesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IntegrantesInclude<ExtArgs> | null
  /**
   * Filter which Integrantes to delete.
   */
  where: Prisma.IntegrantesWhereUniqueInput
}

/**
 * Integrantes deleteMany
 */
export type IntegrantesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Integrantes to delete
   */
  where?: Prisma.IntegrantesWhereInput
  /**
   * Limit how many Integrantes to delete.
   */
  limit?: number
}

/**
 * Integrantes.Eventos_Integrantes
 */
export type Integrantes$Eventos_IntegrantesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Eventos_Integrantes
   */
  select?: Prisma.Eventos_IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Eventos_Integrantes
   */
  omit?: Prisma.Eventos_IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Eventos_IntegrantesInclude<ExtArgs> | null
  where?: Prisma.Eventos_IntegrantesWhereInput
  orderBy?: Prisma.Eventos_IntegrantesOrderByWithRelationInput | Prisma.Eventos_IntegrantesOrderByWithRelationInput[]
  cursor?: Prisma.Eventos_IntegrantesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Eventos_IntegrantesScalarFieldEnum | Prisma.Eventos_IntegrantesScalarFieldEnum[]
}

/**
 * Integrantes.Integrantes_Funcoes
 */
export type Integrantes$Integrantes_FuncoesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesInclude<ExtArgs> | null
  where?: Prisma.Integrantes_FuncoesWhereInput
  orderBy?: Prisma.Integrantes_FuncoesOrderByWithRelationInput | Prisma.Integrantes_FuncoesOrderByWithRelationInput[]
  cursor?: Prisma.Integrantes_FuncoesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Integrantes_FuncoesScalarFieldEnum | Prisma.Integrantes_FuncoesScalarFieldEnum[]
}

/**
 * Integrantes without action
 */
export type IntegrantesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes
   */
  select?: Prisma.IntegrantesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes
   */
  omit?: Prisma.IntegrantesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IntegrantesInclude<ExtArgs> | null
}
