
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Integrantes_Funcoes` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Integrantes_Funcoes
 * 
 */
export type Integrantes_FuncoesModel = runtime.Types.Result.DefaultSelection<Prisma.$Integrantes_FuncoesPayload>

export type AggregateIntegrantes_Funcoes = {
  _count: Integrantes_FuncoesCountAggregateOutputType | null
  _min: Integrantes_FuncoesMinAggregateOutputType | null
  _max: Integrantes_FuncoesMaxAggregateOutputType | null
}

export type Integrantes_FuncoesMinAggregateOutputType = {
  id: string | null
  musico_id: string | null
  funcao_id: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Integrantes_FuncoesMaxAggregateOutputType = {
  id: string | null
  musico_id: string | null
  funcao_id: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Integrantes_FuncoesCountAggregateOutputType = {
  id: number
  musico_id: number
  funcao_id: number
  created_at: number
  updated_at: number
  _all: number
}


export type Integrantes_FuncoesMinAggregateInputType = {
  id?: true
  musico_id?: true
  funcao_id?: true
  created_at?: true
  updated_at?: true
}

export type Integrantes_FuncoesMaxAggregateInputType = {
  id?: true
  musico_id?: true
  funcao_id?: true
  created_at?: true
  updated_at?: true
}

export type Integrantes_FuncoesCountAggregateInputType = {
  id?: true
  musico_id?: true
  funcao_id?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Integrantes_FuncoesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Integrantes_Funcoes to aggregate.
   */
  where?: Prisma.Integrantes_FuncoesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Integrantes_Funcoes to fetch.
   */
  orderBy?: Prisma.Integrantes_FuncoesOrderByWithRelationInput | Prisma.Integrantes_FuncoesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.Integrantes_FuncoesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Integrantes_Funcoes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Integrantes_Funcoes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Integrantes_Funcoes
  **/
  _count?: true | Integrantes_FuncoesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Integrantes_FuncoesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Integrantes_FuncoesMaxAggregateInputType
}

export type GetIntegrantes_FuncoesAggregateType<T extends Integrantes_FuncoesAggregateArgs> = {
      [P in keyof T & keyof AggregateIntegrantes_Funcoes]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIntegrantes_Funcoes[P]>
    : Prisma.GetScalarType<T[P], AggregateIntegrantes_Funcoes[P]>
}




export type Integrantes_FuncoesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.Integrantes_FuncoesWhereInput
  orderBy?: Prisma.Integrantes_FuncoesOrderByWithAggregationInput | Prisma.Integrantes_FuncoesOrderByWithAggregationInput[]
  by: Prisma.Integrantes_FuncoesScalarFieldEnum[] | Prisma.Integrantes_FuncoesScalarFieldEnum
  having?: Prisma.Integrantes_FuncoesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Integrantes_FuncoesCountAggregateInputType | true
  _min?: Integrantes_FuncoesMinAggregateInputType
  _max?: Integrantes_FuncoesMaxAggregateInputType
}

export type Integrantes_FuncoesGroupByOutputType = {
  id: string
  musico_id: string
  funcao_id: string
  created_at: Date
  updated_at: Date
  _count: Integrantes_FuncoesCountAggregateOutputType | null
  _min: Integrantes_FuncoesMinAggregateOutputType | null
  _max: Integrantes_FuncoesMaxAggregateOutputType | null
}

type GetIntegrantes_FuncoesGroupByPayload<T extends Integrantes_FuncoesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Integrantes_FuncoesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Integrantes_FuncoesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Integrantes_FuncoesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Integrantes_FuncoesGroupByOutputType[P]>
      }
    >
  >



export type Integrantes_FuncoesWhereInput = {
  AND?: Prisma.Integrantes_FuncoesWhereInput | Prisma.Integrantes_FuncoesWhereInput[]
  OR?: Prisma.Integrantes_FuncoesWhereInput[]
  NOT?: Prisma.Integrantes_FuncoesWhereInput | Prisma.Integrantes_FuncoesWhereInput[]
  id?: Prisma.UuidFilter<"Integrantes_Funcoes"> | string
  musico_id?: Prisma.UuidFilter<"Integrantes_Funcoes"> | string
  funcao_id?: Prisma.UuidFilter<"Integrantes_Funcoes"> | string
  created_at?: Prisma.DateTimeFilter<"Integrantes_Funcoes"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Integrantes_Funcoes"> | Date | string
  integrantes_funcoes_funcao_id_fkey?: Prisma.XOR<Prisma.FuncoesScalarRelationFilter, Prisma.FuncoesWhereInput>
  integrantes_funcoes_musico_id_fkey?: Prisma.XOR<Prisma.IntegrantesScalarRelationFilter, Prisma.IntegrantesWhereInput>
}

export type Integrantes_FuncoesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  musico_id?: Prisma.SortOrder
  funcao_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  integrantes_funcoes_funcao_id_fkey?: Prisma.FuncoesOrderByWithRelationInput
  integrantes_funcoes_musico_id_fkey?: Prisma.IntegrantesOrderByWithRelationInput
}

export type Integrantes_FuncoesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.Integrantes_FuncoesWhereInput | Prisma.Integrantes_FuncoesWhereInput[]
  OR?: Prisma.Integrantes_FuncoesWhereInput[]
  NOT?: Prisma.Integrantes_FuncoesWhereInput | Prisma.Integrantes_FuncoesWhereInput[]
  musico_id?: Prisma.UuidFilter<"Integrantes_Funcoes"> | string
  funcao_id?: Prisma.UuidFilter<"Integrantes_Funcoes"> | string
  created_at?: Prisma.DateTimeFilter<"Integrantes_Funcoes"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Integrantes_Funcoes"> | Date | string
  integrantes_funcoes_funcao_id_fkey?: Prisma.XOR<Prisma.FuncoesScalarRelationFilter, Prisma.FuncoesWhereInput>
  integrantes_funcoes_musico_id_fkey?: Prisma.XOR<Prisma.IntegrantesScalarRelationFilter, Prisma.IntegrantesWhereInput>
}, "id">

export type Integrantes_FuncoesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  musico_id?: Prisma.SortOrder
  funcao_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.Integrantes_FuncoesCountOrderByAggregateInput
  _max?: Prisma.Integrantes_FuncoesMaxOrderByAggregateInput
  _min?: Prisma.Integrantes_FuncoesMinOrderByAggregateInput
}

export type Integrantes_FuncoesScalarWhereWithAggregatesInput = {
  AND?: Prisma.Integrantes_FuncoesScalarWhereWithAggregatesInput | Prisma.Integrantes_FuncoesScalarWhereWithAggregatesInput[]
  OR?: Prisma.Integrantes_FuncoesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.Integrantes_FuncoesScalarWhereWithAggregatesInput | Prisma.Integrantes_FuncoesScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Integrantes_Funcoes"> | string
  musico_id?: Prisma.UuidWithAggregatesFilter<"Integrantes_Funcoes"> | string
  funcao_id?: Prisma.UuidWithAggregatesFilter<"Integrantes_Funcoes"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Integrantes_Funcoes"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Integrantes_Funcoes"> | Date | string
}

export type Integrantes_FuncoesCreateInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  integrantes_funcoes_funcao_id_fkey: Prisma.FuncoesCreateNestedOneWithoutIntegrantes_FuncoesInput
  integrantes_funcoes_musico_id_fkey: Prisma.IntegrantesCreateNestedOneWithoutIntegrantes_FuncoesInput
}

export type Integrantes_FuncoesUncheckedCreateInput = {
  id?: string
  musico_id: string
  funcao_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Integrantes_FuncoesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  integrantes_funcoes_funcao_id_fkey?: Prisma.FuncoesUpdateOneRequiredWithoutIntegrantes_FuncoesNestedInput
  integrantes_funcoes_musico_id_fkey?: Prisma.IntegrantesUpdateOneRequiredWithoutIntegrantes_FuncoesNestedInput
}

export type Integrantes_FuncoesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  musico_id?: Prisma.StringFieldUpdateOperationsInput | string
  funcao_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Integrantes_FuncoesCreateManyInput = {
  id?: string
  musico_id: string
  funcao_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Integrantes_FuncoesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Integrantes_FuncoesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  musico_id?: Prisma.StringFieldUpdateOperationsInput | string
  funcao_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Integrantes_FuncoesListRelationFilter = {
  every?: Prisma.Integrantes_FuncoesWhereInput
  some?: Prisma.Integrantes_FuncoesWhereInput
  none?: Prisma.Integrantes_FuncoesWhereInput
}

export type Integrantes_FuncoesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type Integrantes_FuncoesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  musico_id?: Prisma.SortOrder
  funcao_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type Integrantes_FuncoesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  musico_id?: Prisma.SortOrder
  funcao_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type Integrantes_FuncoesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  musico_id?: Prisma.SortOrder
  funcao_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type Integrantes_FuncoesCreateNestedManyWithoutIntegrantes_funcoes_funcao_id_fkeyInput = {
  create?: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput> | Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput[] | Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  connectOrCreate?: Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_funcao_id_fkeyInput | Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  createMany?: Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_funcao_id_fkeyInputEnvelope
  connect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
}

export type Integrantes_FuncoesUncheckedCreateNestedManyWithoutIntegrantes_funcoes_funcao_id_fkeyInput = {
  create?: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput> | Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput[] | Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  connectOrCreate?: Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_funcao_id_fkeyInput | Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  createMany?: Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_funcao_id_fkeyInputEnvelope
  connect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
}

export type Integrantes_FuncoesUpdateManyWithoutIntegrantes_funcoes_funcao_id_fkeyNestedInput = {
  create?: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput> | Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput[] | Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  connectOrCreate?: Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_funcao_id_fkeyInput | Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  upsert?: Prisma.Integrantes_FuncoesUpsertWithWhereUniqueWithoutIntegrantes_funcoes_funcao_id_fkeyInput | Prisma.Integrantes_FuncoesUpsertWithWhereUniqueWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  createMany?: Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_funcao_id_fkeyInputEnvelope
  set?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  disconnect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  delete?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  connect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  update?: Prisma.Integrantes_FuncoesUpdateWithWhereUniqueWithoutIntegrantes_funcoes_funcao_id_fkeyInput | Prisma.Integrantes_FuncoesUpdateWithWhereUniqueWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  updateMany?: Prisma.Integrantes_FuncoesUpdateManyWithWhereWithoutIntegrantes_funcoes_funcao_id_fkeyInput | Prisma.Integrantes_FuncoesUpdateManyWithWhereWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  deleteMany?: Prisma.Integrantes_FuncoesScalarWhereInput | Prisma.Integrantes_FuncoesScalarWhereInput[]
}

export type Integrantes_FuncoesUncheckedUpdateManyWithoutIntegrantes_funcoes_funcao_id_fkeyNestedInput = {
  create?: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput> | Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput[] | Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  connectOrCreate?: Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_funcao_id_fkeyInput | Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  upsert?: Prisma.Integrantes_FuncoesUpsertWithWhereUniqueWithoutIntegrantes_funcoes_funcao_id_fkeyInput | Prisma.Integrantes_FuncoesUpsertWithWhereUniqueWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  createMany?: Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_funcao_id_fkeyInputEnvelope
  set?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  disconnect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  delete?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  connect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  update?: Prisma.Integrantes_FuncoesUpdateWithWhereUniqueWithoutIntegrantes_funcoes_funcao_id_fkeyInput | Prisma.Integrantes_FuncoesUpdateWithWhereUniqueWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  updateMany?: Prisma.Integrantes_FuncoesUpdateManyWithWhereWithoutIntegrantes_funcoes_funcao_id_fkeyInput | Prisma.Integrantes_FuncoesUpdateManyWithWhereWithoutIntegrantes_funcoes_funcao_id_fkeyInput[]
  deleteMany?: Prisma.Integrantes_FuncoesScalarWhereInput | Prisma.Integrantes_FuncoesScalarWhereInput[]
}

export type Integrantes_FuncoesCreateNestedManyWithoutIntegrantes_funcoes_musico_id_fkeyInput = {
  create?: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput> | Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput[] | Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  connectOrCreate?: Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_musico_id_fkeyInput | Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  createMany?: Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_musico_id_fkeyInputEnvelope
  connect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
}

export type Integrantes_FuncoesUncheckedCreateNestedManyWithoutIntegrantes_funcoes_musico_id_fkeyInput = {
  create?: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput> | Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput[] | Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  connectOrCreate?: Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_musico_id_fkeyInput | Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  createMany?: Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_musico_id_fkeyInputEnvelope
  connect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
}

export type Integrantes_FuncoesUpdateManyWithoutIntegrantes_funcoes_musico_id_fkeyNestedInput = {
  create?: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput> | Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput[] | Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  connectOrCreate?: Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_musico_id_fkeyInput | Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  upsert?: Prisma.Integrantes_FuncoesUpsertWithWhereUniqueWithoutIntegrantes_funcoes_musico_id_fkeyInput | Prisma.Integrantes_FuncoesUpsertWithWhereUniqueWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  createMany?: Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_musico_id_fkeyInputEnvelope
  set?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  disconnect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  delete?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  connect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  update?: Prisma.Integrantes_FuncoesUpdateWithWhereUniqueWithoutIntegrantes_funcoes_musico_id_fkeyInput | Prisma.Integrantes_FuncoesUpdateWithWhereUniqueWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  updateMany?: Prisma.Integrantes_FuncoesUpdateManyWithWhereWithoutIntegrantes_funcoes_musico_id_fkeyInput | Prisma.Integrantes_FuncoesUpdateManyWithWhereWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  deleteMany?: Prisma.Integrantes_FuncoesScalarWhereInput | Prisma.Integrantes_FuncoesScalarWhereInput[]
}

export type Integrantes_FuncoesUncheckedUpdateManyWithoutIntegrantes_funcoes_musico_id_fkeyNestedInput = {
  create?: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput> | Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput[] | Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  connectOrCreate?: Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_musico_id_fkeyInput | Prisma.Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  upsert?: Prisma.Integrantes_FuncoesUpsertWithWhereUniqueWithoutIntegrantes_funcoes_musico_id_fkeyInput | Prisma.Integrantes_FuncoesUpsertWithWhereUniqueWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  createMany?: Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_musico_id_fkeyInputEnvelope
  set?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  disconnect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  delete?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  connect?: Prisma.Integrantes_FuncoesWhereUniqueInput | Prisma.Integrantes_FuncoesWhereUniqueInput[]
  update?: Prisma.Integrantes_FuncoesUpdateWithWhereUniqueWithoutIntegrantes_funcoes_musico_id_fkeyInput | Prisma.Integrantes_FuncoesUpdateWithWhereUniqueWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  updateMany?: Prisma.Integrantes_FuncoesUpdateManyWithWhereWithoutIntegrantes_funcoes_musico_id_fkeyInput | Prisma.Integrantes_FuncoesUpdateManyWithWhereWithoutIntegrantes_funcoes_musico_id_fkeyInput[]
  deleteMany?: Prisma.Integrantes_FuncoesScalarWhereInput | Prisma.Integrantes_FuncoesScalarWhereInput[]
}

export type Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  integrantes_funcoes_musico_id_fkey: Prisma.IntegrantesCreateNestedOneWithoutIntegrantes_FuncoesInput
}

export type Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput = {
  id?: string
  musico_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_funcao_id_fkeyInput = {
  where: Prisma.Integrantes_FuncoesWhereUniqueInput
  create: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput>
}

export type Integrantes_FuncoesCreateManyIntegrantes_funcoes_funcao_id_fkeyInputEnvelope = {
  data: Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_funcao_id_fkeyInput | Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_funcao_id_fkeyInput[]
  skipDuplicates?: boolean
}

export type Integrantes_FuncoesUpsertWithWhereUniqueWithoutIntegrantes_funcoes_funcao_id_fkeyInput = {
  where: Prisma.Integrantes_FuncoesWhereUniqueInput
  update: Prisma.XOR<Prisma.Integrantes_FuncoesUpdateWithoutIntegrantes_funcoes_funcao_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedUpdateWithoutIntegrantes_funcoes_funcao_id_fkeyInput>
  create: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_funcao_id_fkeyInput>
}

export type Integrantes_FuncoesUpdateWithWhereUniqueWithoutIntegrantes_funcoes_funcao_id_fkeyInput = {
  where: Prisma.Integrantes_FuncoesWhereUniqueInput
  data: Prisma.XOR<Prisma.Integrantes_FuncoesUpdateWithoutIntegrantes_funcoes_funcao_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedUpdateWithoutIntegrantes_funcoes_funcao_id_fkeyInput>
}

export type Integrantes_FuncoesUpdateManyWithWhereWithoutIntegrantes_funcoes_funcao_id_fkeyInput = {
  where: Prisma.Integrantes_FuncoesScalarWhereInput
  data: Prisma.XOR<Prisma.Integrantes_FuncoesUpdateManyMutationInput, Prisma.Integrantes_FuncoesUncheckedUpdateManyWithoutIntegrantes_funcoes_funcao_id_fkeyInput>
}

export type Integrantes_FuncoesScalarWhereInput = {
  AND?: Prisma.Integrantes_FuncoesScalarWhereInput | Prisma.Integrantes_FuncoesScalarWhereInput[]
  OR?: Prisma.Integrantes_FuncoesScalarWhereInput[]
  NOT?: Prisma.Integrantes_FuncoesScalarWhereInput | Prisma.Integrantes_FuncoesScalarWhereInput[]
  id?: Prisma.UuidFilter<"Integrantes_Funcoes"> | string
  musico_id?: Prisma.UuidFilter<"Integrantes_Funcoes"> | string
  funcao_id?: Prisma.UuidFilter<"Integrantes_Funcoes"> | string
  created_at?: Prisma.DateTimeFilter<"Integrantes_Funcoes"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Integrantes_Funcoes"> | Date | string
}

export type Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  integrantes_funcoes_funcao_id_fkey: Prisma.FuncoesCreateNestedOneWithoutIntegrantes_FuncoesInput
}

export type Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput = {
  id?: string
  funcao_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Integrantes_FuncoesCreateOrConnectWithoutIntegrantes_funcoes_musico_id_fkeyInput = {
  where: Prisma.Integrantes_FuncoesWhereUniqueInput
  create: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput>
}

export type Integrantes_FuncoesCreateManyIntegrantes_funcoes_musico_id_fkeyInputEnvelope = {
  data: Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_musico_id_fkeyInput | Prisma.Integrantes_FuncoesCreateManyIntegrantes_funcoes_musico_id_fkeyInput[]
  skipDuplicates?: boolean
}

export type Integrantes_FuncoesUpsertWithWhereUniqueWithoutIntegrantes_funcoes_musico_id_fkeyInput = {
  where: Prisma.Integrantes_FuncoesWhereUniqueInput
  update: Prisma.XOR<Prisma.Integrantes_FuncoesUpdateWithoutIntegrantes_funcoes_musico_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedUpdateWithoutIntegrantes_funcoes_musico_id_fkeyInput>
  create: Prisma.XOR<Prisma.Integrantes_FuncoesCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedCreateWithoutIntegrantes_funcoes_musico_id_fkeyInput>
}

export type Integrantes_FuncoesUpdateWithWhereUniqueWithoutIntegrantes_funcoes_musico_id_fkeyInput = {
  where: Prisma.Integrantes_FuncoesWhereUniqueInput
  data: Prisma.XOR<Prisma.Integrantes_FuncoesUpdateWithoutIntegrantes_funcoes_musico_id_fkeyInput, Prisma.Integrantes_FuncoesUncheckedUpdateWithoutIntegrantes_funcoes_musico_id_fkeyInput>
}

export type Integrantes_FuncoesUpdateManyWithWhereWithoutIntegrantes_funcoes_musico_id_fkeyInput = {
  where: Prisma.Integrantes_FuncoesScalarWhereInput
  data: Prisma.XOR<Prisma.Integrantes_FuncoesUpdateManyMutationInput, Prisma.Integrantes_FuncoesUncheckedUpdateManyWithoutIntegrantes_funcoes_musico_id_fkeyInput>
}

export type Integrantes_FuncoesCreateManyIntegrantes_funcoes_funcao_id_fkeyInput = {
  id?: string
  musico_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Integrantes_FuncoesUpdateWithoutIntegrantes_funcoes_funcao_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  integrantes_funcoes_musico_id_fkey?: Prisma.IntegrantesUpdateOneRequiredWithoutIntegrantes_FuncoesNestedInput
}

export type Integrantes_FuncoesUncheckedUpdateWithoutIntegrantes_funcoes_funcao_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  musico_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Integrantes_FuncoesUncheckedUpdateManyWithoutIntegrantes_funcoes_funcao_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  musico_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Integrantes_FuncoesCreateManyIntegrantes_funcoes_musico_id_fkeyInput = {
  id?: string
  funcao_id: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type Integrantes_FuncoesUpdateWithoutIntegrantes_funcoes_musico_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  integrantes_funcoes_funcao_id_fkey?: Prisma.FuncoesUpdateOneRequiredWithoutIntegrantes_FuncoesNestedInput
}

export type Integrantes_FuncoesUncheckedUpdateWithoutIntegrantes_funcoes_musico_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  funcao_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Integrantes_FuncoesUncheckedUpdateManyWithoutIntegrantes_funcoes_musico_id_fkeyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  funcao_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type Integrantes_FuncoesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  musico_id?: boolean
  funcao_id?: boolean
  created_at?: boolean
  updated_at?: boolean
  integrantes_funcoes_funcao_id_fkey?: boolean | Prisma.FuncoesDefaultArgs<ExtArgs>
  integrantes_funcoes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["integrantes_Funcoes"]>

export type Integrantes_FuncoesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  musico_id?: boolean
  funcao_id?: boolean
  created_at?: boolean
  updated_at?: boolean
  integrantes_funcoes_funcao_id_fkey?: boolean | Prisma.FuncoesDefaultArgs<ExtArgs>
  integrantes_funcoes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["integrantes_Funcoes"]>

export type Integrantes_FuncoesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  musico_id?: boolean
  funcao_id?: boolean
  created_at?: boolean
  updated_at?: boolean
  integrantes_funcoes_funcao_id_fkey?: boolean | Prisma.FuncoesDefaultArgs<ExtArgs>
  integrantes_funcoes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["integrantes_Funcoes"]>

export type Integrantes_FuncoesSelectScalar = {
  id?: boolean
  musico_id?: boolean
  funcao_id?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type Integrantes_FuncoesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "musico_id" | "funcao_id" | "created_at" | "updated_at", ExtArgs["result"]["integrantes_Funcoes"]>
export type Integrantes_FuncoesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  integrantes_funcoes_funcao_id_fkey?: boolean | Prisma.FuncoesDefaultArgs<ExtArgs>
  integrantes_funcoes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}
export type Integrantes_FuncoesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  integrantes_funcoes_funcao_id_fkey?: boolean | Prisma.FuncoesDefaultArgs<ExtArgs>
  integrantes_funcoes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}
export type Integrantes_FuncoesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  integrantes_funcoes_funcao_id_fkey?: boolean | Prisma.FuncoesDefaultArgs<ExtArgs>
  integrantes_funcoes_musico_id_fkey?: boolean | Prisma.IntegrantesDefaultArgs<ExtArgs>
}

export type $Integrantes_FuncoesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Integrantes_Funcoes"
  objects: {
    integrantes_funcoes_funcao_id_fkey: Prisma.$FuncoesPayload<ExtArgs>
    integrantes_funcoes_musico_id_fkey: Prisma.$IntegrantesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    musico_id: string
    funcao_id: string
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["integrantes_Funcoes"]>
  composites: {}
}

export type Integrantes_FuncoesGetPayload<S extends boolean | null | undefined | Integrantes_FuncoesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload, S>

export type Integrantes_FuncoesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<Integrantes_FuncoesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Integrantes_FuncoesCountAggregateInputType | true
  }

export interface Integrantes_FuncoesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Integrantes_Funcoes'], meta: { name: 'Integrantes_Funcoes' } }
  /**
   * Find zero or one Integrantes_Funcoes that matches the filter.
   * @param {Integrantes_FuncoesFindUniqueArgs} args - Arguments to find a Integrantes_Funcoes
   * @example
   * // Get one Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends Integrantes_FuncoesFindUniqueArgs>(args: Prisma.SelectSubset<T, Integrantes_FuncoesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__Integrantes_FuncoesClient<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Integrantes_Funcoes that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {Integrantes_FuncoesFindUniqueOrThrowArgs} args - Arguments to find a Integrantes_Funcoes
   * @example
   * // Get one Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends Integrantes_FuncoesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Integrantes_FuncoesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__Integrantes_FuncoesClient<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Integrantes_Funcoes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Integrantes_FuncoesFindFirstArgs} args - Arguments to find a Integrantes_Funcoes
   * @example
   * // Get one Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends Integrantes_FuncoesFindFirstArgs>(args?: Prisma.SelectSubset<T, Integrantes_FuncoesFindFirstArgs<ExtArgs>>): Prisma.Prisma__Integrantes_FuncoesClient<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Integrantes_Funcoes that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Integrantes_FuncoesFindFirstOrThrowArgs} args - Arguments to find a Integrantes_Funcoes
   * @example
   * // Get one Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends Integrantes_FuncoesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, Integrantes_FuncoesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__Integrantes_FuncoesClient<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Integrantes_Funcoes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Integrantes_FuncoesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.findMany()
   * 
   * // Get first 10 Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const integrantes_FuncoesWithIdOnly = await prisma.integrantes_Funcoes.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends Integrantes_FuncoesFindManyArgs>(args?: Prisma.SelectSubset<T, Integrantes_FuncoesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Integrantes_Funcoes.
   * @param {Integrantes_FuncoesCreateArgs} args - Arguments to create a Integrantes_Funcoes.
   * @example
   * // Create one Integrantes_Funcoes
   * const Integrantes_Funcoes = await prisma.integrantes_Funcoes.create({
   *   data: {
   *     // ... data to create a Integrantes_Funcoes
   *   }
   * })
   * 
   */
  create<T extends Integrantes_FuncoesCreateArgs>(args: Prisma.SelectSubset<T, Integrantes_FuncoesCreateArgs<ExtArgs>>): Prisma.Prisma__Integrantes_FuncoesClient<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Integrantes_Funcoes.
   * @param {Integrantes_FuncoesCreateManyArgs} args - Arguments to create many Integrantes_Funcoes.
   * @example
   * // Create many Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends Integrantes_FuncoesCreateManyArgs>(args?: Prisma.SelectSubset<T, Integrantes_FuncoesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Integrantes_Funcoes and returns the data saved in the database.
   * @param {Integrantes_FuncoesCreateManyAndReturnArgs} args - Arguments to create many Integrantes_Funcoes.
   * @example
   * // Create many Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Integrantes_Funcoes and only return the `id`
   * const integrantes_FuncoesWithIdOnly = await prisma.integrantes_Funcoes.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends Integrantes_FuncoesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, Integrantes_FuncoesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Integrantes_Funcoes.
   * @param {Integrantes_FuncoesDeleteArgs} args - Arguments to delete one Integrantes_Funcoes.
   * @example
   * // Delete one Integrantes_Funcoes
   * const Integrantes_Funcoes = await prisma.integrantes_Funcoes.delete({
   *   where: {
   *     // ... filter to delete one Integrantes_Funcoes
   *   }
   * })
   * 
   */
  delete<T extends Integrantes_FuncoesDeleteArgs>(args: Prisma.SelectSubset<T, Integrantes_FuncoesDeleteArgs<ExtArgs>>): Prisma.Prisma__Integrantes_FuncoesClient<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Integrantes_Funcoes.
   * @param {Integrantes_FuncoesUpdateArgs} args - Arguments to update one Integrantes_Funcoes.
   * @example
   * // Update one Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends Integrantes_FuncoesUpdateArgs>(args: Prisma.SelectSubset<T, Integrantes_FuncoesUpdateArgs<ExtArgs>>): Prisma.Prisma__Integrantes_FuncoesClient<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Integrantes_Funcoes.
   * @param {Integrantes_FuncoesDeleteManyArgs} args - Arguments to filter Integrantes_Funcoes to delete.
   * @example
   * // Delete a few Integrantes_Funcoes
   * const { count } = await prisma.integrantes_Funcoes.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends Integrantes_FuncoesDeleteManyArgs>(args?: Prisma.SelectSubset<T, Integrantes_FuncoesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Integrantes_Funcoes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Integrantes_FuncoesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends Integrantes_FuncoesUpdateManyArgs>(args: Prisma.SelectSubset<T, Integrantes_FuncoesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Integrantes_Funcoes and returns the data updated in the database.
   * @param {Integrantes_FuncoesUpdateManyAndReturnArgs} args - Arguments to update many Integrantes_Funcoes.
   * @example
   * // Update many Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Integrantes_Funcoes and only return the `id`
   * const integrantes_FuncoesWithIdOnly = await prisma.integrantes_Funcoes.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends Integrantes_FuncoesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Integrantes_FuncoesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Integrantes_Funcoes.
   * @param {Integrantes_FuncoesUpsertArgs} args - Arguments to update or create a Integrantes_Funcoes.
   * @example
   * // Update or create a Integrantes_Funcoes
   * const integrantes_Funcoes = await prisma.integrantes_Funcoes.upsert({
   *   create: {
   *     // ... data to create a Integrantes_Funcoes
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Integrantes_Funcoes we want to update
   *   }
   * })
   */
  upsert<T extends Integrantes_FuncoesUpsertArgs>(args: Prisma.SelectSubset<T, Integrantes_FuncoesUpsertArgs<ExtArgs>>): Prisma.Prisma__Integrantes_FuncoesClient<runtime.Types.Result.GetResult<Prisma.$Integrantes_FuncoesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Integrantes_Funcoes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Integrantes_FuncoesCountArgs} args - Arguments to filter Integrantes_Funcoes to count.
   * @example
   * // Count the number of Integrantes_Funcoes
   * const count = await prisma.integrantes_Funcoes.count({
   *   where: {
   *     // ... the filter for the Integrantes_Funcoes we want to count
   *   }
   * })
  **/
  count<T extends Integrantes_FuncoesCountArgs>(
    args?: Prisma.Subset<T, Integrantes_FuncoesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Integrantes_FuncoesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Integrantes_Funcoes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Integrantes_FuncoesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Integrantes_FuncoesAggregateArgs>(args: Prisma.Subset<T, Integrantes_FuncoesAggregateArgs>): Prisma.PrismaPromise<GetIntegrantes_FuncoesAggregateType<T>>

  /**
   * Group by Integrantes_Funcoes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Integrantes_FuncoesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends Integrantes_FuncoesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: Integrantes_FuncoesGroupByArgs['orderBy'] }
      : { orderBy?: Integrantes_FuncoesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, Integrantes_FuncoesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIntegrantes_FuncoesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Integrantes_Funcoes model
 */
readonly fields: Integrantes_FuncoesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Integrantes_Funcoes.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__Integrantes_FuncoesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  integrantes_funcoes_funcao_id_fkey<T extends Prisma.FuncoesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FuncoesDefaultArgs<ExtArgs>>): Prisma.Prisma__FuncoesClient<runtime.Types.Result.GetResult<Prisma.$FuncoesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  integrantes_funcoes_musico_id_fkey<T extends Prisma.IntegrantesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.IntegrantesDefaultArgs<ExtArgs>>): Prisma.Prisma__IntegrantesClient<runtime.Types.Result.GetResult<Prisma.$IntegrantesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Integrantes_Funcoes model
 */
export interface Integrantes_FuncoesFieldRefs {
  readonly id: Prisma.FieldRef<"Integrantes_Funcoes", 'String'>
  readonly musico_id: Prisma.FieldRef<"Integrantes_Funcoes", 'String'>
  readonly funcao_id: Prisma.FieldRef<"Integrantes_Funcoes", 'String'>
  readonly created_at: Prisma.FieldRef<"Integrantes_Funcoes", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Integrantes_Funcoes", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Integrantes_Funcoes findUnique
 */
export type Integrantes_FuncoesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesInclude<ExtArgs> | null
  /**
   * Filter, which Integrantes_Funcoes to fetch.
   */
  where: Prisma.Integrantes_FuncoesWhereUniqueInput
}

/**
 * Integrantes_Funcoes findUniqueOrThrow
 */
export type Integrantes_FuncoesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesInclude<ExtArgs> | null
  /**
   * Filter, which Integrantes_Funcoes to fetch.
   */
  where: Prisma.Integrantes_FuncoesWhereUniqueInput
}

/**
 * Integrantes_Funcoes findFirst
 */
export type Integrantes_FuncoesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesInclude<ExtArgs> | null
  /**
   * Filter, which Integrantes_Funcoes to fetch.
   */
  where?: Prisma.Integrantes_FuncoesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Integrantes_Funcoes to fetch.
   */
  orderBy?: Prisma.Integrantes_FuncoesOrderByWithRelationInput | Prisma.Integrantes_FuncoesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Integrantes_Funcoes.
   */
  cursor?: Prisma.Integrantes_FuncoesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Integrantes_Funcoes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Integrantes_Funcoes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Integrantes_Funcoes.
   */
  distinct?: Prisma.Integrantes_FuncoesScalarFieldEnum | Prisma.Integrantes_FuncoesScalarFieldEnum[]
}

/**
 * Integrantes_Funcoes findFirstOrThrow
 */
export type Integrantes_FuncoesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesInclude<ExtArgs> | null
  /**
   * Filter, which Integrantes_Funcoes to fetch.
   */
  where?: Prisma.Integrantes_FuncoesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Integrantes_Funcoes to fetch.
   */
  orderBy?: Prisma.Integrantes_FuncoesOrderByWithRelationInput | Prisma.Integrantes_FuncoesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Integrantes_Funcoes.
   */
  cursor?: Prisma.Integrantes_FuncoesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Integrantes_Funcoes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Integrantes_Funcoes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Integrantes_Funcoes.
   */
  distinct?: Prisma.Integrantes_FuncoesScalarFieldEnum | Prisma.Integrantes_FuncoesScalarFieldEnum[]
}

/**
 * Integrantes_Funcoes findMany
 */
export type Integrantes_FuncoesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesInclude<ExtArgs> | null
  /**
   * Filter, which Integrantes_Funcoes to fetch.
   */
  where?: Prisma.Integrantes_FuncoesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Integrantes_Funcoes to fetch.
   */
  orderBy?: Prisma.Integrantes_FuncoesOrderByWithRelationInput | Prisma.Integrantes_FuncoesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Integrantes_Funcoes.
   */
  cursor?: Prisma.Integrantes_FuncoesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Integrantes_Funcoes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Integrantes_Funcoes.
   */
  skip?: number
  distinct?: Prisma.Integrantes_FuncoesScalarFieldEnum | Prisma.Integrantes_FuncoesScalarFieldEnum[]
}

/**
 * Integrantes_Funcoes create
 */
export type Integrantes_FuncoesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesInclude<ExtArgs> | null
  /**
   * The data needed to create a Integrantes_Funcoes.
   */
  data: Prisma.XOR<Prisma.Integrantes_FuncoesCreateInput, Prisma.Integrantes_FuncoesUncheckedCreateInput>
}

/**
 * Integrantes_Funcoes createMany
 */
export type Integrantes_FuncoesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Integrantes_Funcoes.
   */
  data: Prisma.Integrantes_FuncoesCreateManyInput | Prisma.Integrantes_FuncoesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Integrantes_Funcoes createManyAndReturn
 */
export type Integrantes_FuncoesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * The data used to create many Integrantes_Funcoes.
   */
  data: Prisma.Integrantes_FuncoesCreateManyInput | Prisma.Integrantes_FuncoesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Integrantes_Funcoes update
 */
export type Integrantes_FuncoesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesInclude<ExtArgs> | null
  /**
   * The data needed to update a Integrantes_Funcoes.
   */
  data: Prisma.XOR<Prisma.Integrantes_FuncoesUpdateInput, Prisma.Integrantes_FuncoesUncheckedUpdateInput>
  /**
   * Choose, which Integrantes_Funcoes to update.
   */
  where: Prisma.Integrantes_FuncoesWhereUniqueInput
}

/**
 * Integrantes_Funcoes updateMany
 */
export type Integrantes_FuncoesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Integrantes_Funcoes.
   */
  data: Prisma.XOR<Prisma.Integrantes_FuncoesUpdateManyMutationInput, Prisma.Integrantes_FuncoesUncheckedUpdateManyInput>
  /**
   * Filter which Integrantes_Funcoes to update
   */
  where?: Prisma.Integrantes_FuncoesWhereInput
  /**
   * Limit how many Integrantes_Funcoes to update.
   */
  limit?: number
}

/**
 * Integrantes_Funcoes updateManyAndReturn
 */
export type Integrantes_FuncoesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * The data used to update Integrantes_Funcoes.
   */
  data: Prisma.XOR<Prisma.Integrantes_FuncoesUpdateManyMutationInput, Prisma.Integrantes_FuncoesUncheckedUpdateManyInput>
  /**
   * Filter which Integrantes_Funcoes to update
   */
  where?: Prisma.Integrantes_FuncoesWhereInput
  /**
   * Limit how many Integrantes_Funcoes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Integrantes_Funcoes upsert
 */
export type Integrantes_FuncoesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesInclude<ExtArgs> | null
  /**
   * The filter to search for the Integrantes_Funcoes to update in case it exists.
   */
  where: Prisma.Integrantes_FuncoesWhereUniqueInput
  /**
   * In case the Integrantes_Funcoes found by the `where` argument doesn't exist, create a new Integrantes_Funcoes with this data.
   */
  create: Prisma.XOR<Prisma.Integrantes_FuncoesCreateInput, Prisma.Integrantes_FuncoesUncheckedCreateInput>
  /**
   * In case the Integrantes_Funcoes was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.Integrantes_FuncoesUpdateInput, Prisma.Integrantes_FuncoesUncheckedUpdateInput>
}

/**
 * Integrantes_Funcoes delete
 */
export type Integrantes_FuncoesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesInclude<ExtArgs> | null
  /**
   * Filter which Integrantes_Funcoes to delete.
   */
  where: Prisma.Integrantes_FuncoesWhereUniqueInput
}

/**
 * Integrantes_Funcoes deleteMany
 */
export type Integrantes_FuncoesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Integrantes_Funcoes to delete
   */
  where?: Prisma.Integrantes_FuncoesWhereInput
  /**
   * Limit how many Integrantes_Funcoes to delete.
   */
  limit?: number
}

/**
 * Integrantes_Funcoes without action
 */
export type Integrantes_FuncoesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Integrantes_Funcoes
   */
  select?: Prisma.Integrantes_FuncoesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Integrantes_Funcoes
   */
  omit?: Prisma.Integrantes_FuncoesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.Integrantes_FuncoesInclude<ExtArgs> | null
}
