
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Tonalidades` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Tonalidades
 * 
 */
export type TonalidadesModel = runtime.Types.Result.DefaultSelection<Prisma.$TonalidadesPayload>

export type AggregateTonalidades = {
  _count: TonalidadesCountAggregateOutputType | null
  _min: TonalidadesMinAggregateOutputType | null
  _max: TonalidadesMaxAggregateOutputType | null
}

export type TonalidadesMinAggregateOutputType = {
  id: string | null
  tom: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type TonalidadesMaxAggregateOutputType = {
  id: string | null
  tom: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type TonalidadesCountAggregateOutputType = {
  id: number
  tom: number
  created_at: number
  updated_at: number
  _all: number
}


export type TonalidadesMinAggregateInputType = {
  id?: true
  tom?: true
  created_at?: true
  updated_at?: true
}

export type TonalidadesMaxAggregateInputType = {
  id?: true
  tom?: true
  created_at?: true
  updated_at?: true
}

export type TonalidadesCountAggregateInputType = {
  id?: true
  tom?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type TonalidadesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tonalidades to aggregate.
   */
  where?: Prisma.TonalidadesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tonalidades to fetch.
   */
  orderBy?: Prisma.TonalidadesOrderByWithRelationInput | Prisma.TonalidadesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TonalidadesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tonalidades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tonalidades.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tonalidades
  **/
  _count?: true | TonalidadesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TonalidadesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TonalidadesMaxAggregateInputType
}

export type GetTonalidadesAggregateType<T extends TonalidadesAggregateArgs> = {
      [P in keyof T & keyof AggregateTonalidades]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTonalidades[P]>
    : Prisma.GetScalarType<T[P], AggregateTonalidades[P]>
}




export type TonalidadesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TonalidadesWhereInput
  orderBy?: Prisma.TonalidadesOrderByWithAggregationInput | Prisma.TonalidadesOrderByWithAggregationInput[]
  by: Prisma.TonalidadesScalarFieldEnum[] | Prisma.TonalidadesScalarFieldEnum
  having?: Prisma.TonalidadesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TonalidadesCountAggregateInputType | true
  _min?: TonalidadesMinAggregateInputType
  _max?: TonalidadesMaxAggregateInputType
}

export type TonalidadesGroupByOutputType = {
  id: string
  tom: string
  created_at: Date
  updated_at: Date
  _count: TonalidadesCountAggregateOutputType | null
  _min: TonalidadesMinAggregateOutputType | null
  _max: TonalidadesMaxAggregateOutputType | null
}

type GetTonalidadesGroupByPayload<T extends TonalidadesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TonalidadesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TonalidadesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TonalidadesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TonalidadesGroupByOutputType[P]>
      }
    >
  >



export type TonalidadesWhereInput = {
  AND?: Prisma.TonalidadesWhereInput | Prisma.TonalidadesWhereInput[]
  OR?: Prisma.TonalidadesWhereInput[]
  NOT?: Prisma.TonalidadesWhereInput | Prisma.TonalidadesWhereInput[]
  id?: Prisma.UuidFilter<"Tonalidades"> | string
  tom?: Prisma.StringFilter<"Tonalidades"> | string
  created_at?: Prisma.DateTimeFilter<"Tonalidades"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Tonalidades"> | Date | string
  Musicas?: Prisma.MusicasListRelationFilter
}

export type TonalidadesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tom?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  Musicas?: Prisma.MusicasOrderByRelationAggregateInput
}

export type TonalidadesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TonalidadesWhereInput | Prisma.TonalidadesWhereInput[]
  OR?: Prisma.TonalidadesWhereInput[]
  NOT?: Prisma.TonalidadesWhereInput | Prisma.TonalidadesWhereInput[]
  tom?: Prisma.StringFilter<"Tonalidades"> | string
  created_at?: Prisma.DateTimeFilter<"Tonalidades"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Tonalidades"> | Date | string
  Musicas?: Prisma.MusicasListRelationFilter
}, "id">

export type TonalidadesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tom?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.TonalidadesCountOrderByAggregateInput
  _max?: Prisma.TonalidadesMaxOrderByAggregateInput
  _min?: Prisma.TonalidadesMinOrderByAggregateInput
}

export type TonalidadesScalarWhereWithAggregatesInput = {
  AND?: Prisma.TonalidadesScalarWhereWithAggregatesInput | Prisma.TonalidadesScalarWhereWithAggregatesInput[]
  OR?: Prisma.TonalidadesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TonalidadesScalarWhereWithAggregatesInput | Prisma.TonalidadesScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Tonalidades"> | string
  tom?: Prisma.StringWithAggregatesFilter<"Tonalidades"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Tonalidades"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Tonalidades"> | Date | string
}

export type TonalidadesCreateInput = {
  id?: string
  tom: string
  created_at?: Date | string
  updated_at?: Date | string
  Musicas?: Prisma.MusicasCreateNestedManyWithoutMusicas_fk_tonalidade_fkeyInput
}

export type TonalidadesUncheckedCreateInput = {
  id?: string
  tom: string
  created_at?: Date | string
  updated_at?: Date | string
  Musicas?: Prisma.MusicasUncheckedCreateNestedManyWithoutMusicas_fk_tonalidade_fkeyInput
}

export type TonalidadesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tom?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Musicas?: Prisma.MusicasUpdateManyWithoutMusicas_fk_tonalidade_fkeyNestedInput
}

export type TonalidadesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tom?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Musicas?: Prisma.MusicasUncheckedUpdateManyWithoutMusicas_fk_tonalidade_fkeyNestedInput
}

export type TonalidadesCreateManyInput = {
  id?: string
  tom: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type TonalidadesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tom?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TonalidadesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tom?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TonalidadesScalarRelationFilter = {
  is?: Prisma.TonalidadesWhereInput
  isNot?: Prisma.TonalidadesWhereInput
}

export type TonalidadesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tom?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type TonalidadesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tom?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type TonalidadesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tom?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type TonalidadesCreateNestedOneWithoutMusicasInput = {
  create?: Prisma.XOR<Prisma.TonalidadesCreateWithoutMusicasInput, Prisma.TonalidadesUncheckedCreateWithoutMusicasInput>
  connectOrCreate?: Prisma.TonalidadesCreateOrConnectWithoutMusicasInput
  connect?: Prisma.TonalidadesWhereUniqueInput
}

export type TonalidadesUpdateOneRequiredWithoutMusicasNestedInput = {
  create?: Prisma.XOR<Prisma.TonalidadesCreateWithoutMusicasInput, Prisma.TonalidadesUncheckedCreateWithoutMusicasInput>
  connectOrCreate?: Prisma.TonalidadesCreateOrConnectWithoutMusicasInput
  upsert?: Prisma.TonalidadesUpsertWithoutMusicasInput
  connect?: Prisma.TonalidadesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TonalidadesUpdateToOneWithWhereWithoutMusicasInput, Prisma.TonalidadesUpdateWithoutMusicasInput>, Prisma.TonalidadesUncheckedUpdateWithoutMusicasInput>
}

export type TonalidadesCreateWithoutMusicasInput = {
  id?: string
  tom: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type TonalidadesUncheckedCreateWithoutMusicasInput = {
  id?: string
  tom: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type TonalidadesCreateOrConnectWithoutMusicasInput = {
  where: Prisma.TonalidadesWhereUniqueInput
  create: Prisma.XOR<Prisma.TonalidadesCreateWithoutMusicasInput, Prisma.TonalidadesUncheckedCreateWithoutMusicasInput>
}

export type TonalidadesUpsertWithoutMusicasInput = {
  update: Prisma.XOR<Prisma.TonalidadesUpdateWithoutMusicasInput, Prisma.TonalidadesUncheckedUpdateWithoutMusicasInput>
  create: Prisma.XOR<Prisma.TonalidadesCreateWithoutMusicasInput, Prisma.TonalidadesUncheckedCreateWithoutMusicasInput>
  where?: Prisma.TonalidadesWhereInput
}

export type TonalidadesUpdateToOneWithWhereWithoutMusicasInput = {
  where?: Prisma.TonalidadesWhereInput
  data: Prisma.XOR<Prisma.TonalidadesUpdateWithoutMusicasInput, Prisma.TonalidadesUncheckedUpdateWithoutMusicasInput>
}

export type TonalidadesUpdateWithoutMusicasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tom?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TonalidadesUncheckedUpdateWithoutMusicasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tom?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TonalidadesCountOutputType
 */

export type TonalidadesCountOutputType = {
  Musicas: number
}

export type TonalidadesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Musicas?: boolean | TonalidadesCountOutputTypeCountMusicasArgs
}

/**
 * TonalidadesCountOutputType without action
 */
export type TonalidadesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TonalidadesCountOutputType
   */
  select?: Prisma.TonalidadesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TonalidadesCountOutputType without action
 */
export type TonalidadesCountOutputTypeCountMusicasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MusicasWhereInput
}


export type TonalidadesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tom?: boolean
  created_at?: boolean
  updated_at?: boolean
  Musicas?: boolean | Prisma.Tonalidades$MusicasArgs<ExtArgs>
  _count?: boolean | Prisma.TonalidadesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tonalidades"]>

export type TonalidadesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tom?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["tonalidades"]>

export type TonalidadesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tom?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["tonalidades"]>

export type TonalidadesSelectScalar = {
  id?: boolean
  tom?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type TonalidadesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tom" | "created_at" | "updated_at", ExtArgs["result"]["tonalidades"]>
export type TonalidadesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Musicas?: boolean | Prisma.Tonalidades$MusicasArgs<ExtArgs>
  _count?: boolean | Prisma.TonalidadesCountOutputTypeDefaultArgs<ExtArgs>
}
export type TonalidadesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TonalidadesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TonalidadesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Tonalidades"
  objects: {
    Musicas: Prisma.$MusicasPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tom: string
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["tonalidades"]>
  composites: {}
}

export type TonalidadesGetPayload<S extends boolean | null | undefined | TonalidadesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload, S>

export type TonalidadesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TonalidadesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TonalidadesCountAggregateInputType | true
  }

export interface TonalidadesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Tonalidades'], meta: { name: 'Tonalidades' } }
  /**
   * Find zero or one Tonalidades that matches the filter.
   * @param {TonalidadesFindUniqueArgs} args - Arguments to find a Tonalidades
   * @example
   * // Get one Tonalidades
   * const tonalidades = await prisma.tonalidades.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TonalidadesFindUniqueArgs>(args: Prisma.SelectSubset<T, TonalidadesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TonalidadesClient<runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tonalidades that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TonalidadesFindUniqueOrThrowArgs} args - Arguments to find a Tonalidades
   * @example
   * // Get one Tonalidades
   * const tonalidades = await prisma.tonalidades.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TonalidadesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TonalidadesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TonalidadesClient<runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tonalidades that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TonalidadesFindFirstArgs} args - Arguments to find a Tonalidades
   * @example
   * // Get one Tonalidades
   * const tonalidades = await prisma.tonalidades.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TonalidadesFindFirstArgs>(args?: Prisma.SelectSubset<T, TonalidadesFindFirstArgs<ExtArgs>>): Prisma.Prisma__TonalidadesClient<runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tonalidades that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TonalidadesFindFirstOrThrowArgs} args - Arguments to find a Tonalidades
   * @example
   * // Get one Tonalidades
   * const tonalidades = await prisma.tonalidades.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TonalidadesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TonalidadesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TonalidadesClient<runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tonalidades that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TonalidadesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tonalidades
   * const tonalidades = await prisma.tonalidades.findMany()
   * 
   * // Get first 10 Tonalidades
   * const tonalidades = await prisma.tonalidades.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tonalidadesWithIdOnly = await prisma.tonalidades.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TonalidadesFindManyArgs>(args?: Prisma.SelectSubset<T, TonalidadesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tonalidades.
   * @param {TonalidadesCreateArgs} args - Arguments to create a Tonalidades.
   * @example
   * // Create one Tonalidades
   * const Tonalidades = await prisma.tonalidades.create({
   *   data: {
   *     // ... data to create a Tonalidades
   *   }
   * })
   * 
   */
  create<T extends TonalidadesCreateArgs>(args: Prisma.SelectSubset<T, TonalidadesCreateArgs<ExtArgs>>): Prisma.Prisma__TonalidadesClient<runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tonalidades.
   * @param {TonalidadesCreateManyArgs} args - Arguments to create many Tonalidades.
   * @example
   * // Create many Tonalidades
   * const tonalidades = await prisma.tonalidades.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TonalidadesCreateManyArgs>(args?: Prisma.SelectSubset<T, TonalidadesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tonalidades and returns the data saved in the database.
   * @param {TonalidadesCreateManyAndReturnArgs} args - Arguments to create many Tonalidades.
   * @example
   * // Create many Tonalidades
   * const tonalidades = await prisma.tonalidades.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tonalidades and only return the `id`
   * const tonalidadesWithIdOnly = await prisma.tonalidades.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TonalidadesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TonalidadesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tonalidades.
   * @param {TonalidadesDeleteArgs} args - Arguments to delete one Tonalidades.
   * @example
   * // Delete one Tonalidades
   * const Tonalidades = await prisma.tonalidades.delete({
   *   where: {
   *     // ... filter to delete one Tonalidades
   *   }
   * })
   * 
   */
  delete<T extends TonalidadesDeleteArgs>(args: Prisma.SelectSubset<T, TonalidadesDeleteArgs<ExtArgs>>): Prisma.Prisma__TonalidadesClient<runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tonalidades.
   * @param {TonalidadesUpdateArgs} args - Arguments to update one Tonalidades.
   * @example
   * // Update one Tonalidades
   * const tonalidades = await prisma.tonalidades.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TonalidadesUpdateArgs>(args: Prisma.SelectSubset<T, TonalidadesUpdateArgs<ExtArgs>>): Prisma.Prisma__TonalidadesClient<runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tonalidades.
   * @param {TonalidadesDeleteManyArgs} args - Arguments to filter Tonalidades to delete.
   * @example
   * // Delete a few Tonalidades
   * const { count } = await prisma.tonalidades.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TonalidadesDeleteManyArgs>(args?: Prisma.SelectSubset<T, TonalidadesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tonalidades.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TonalidadesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tonalidades
   * const tonalidades = await prisma.tonalidades.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TonalidadesUpdateManyArgs>(args: Prisma.SelectSubset<T, TonalidadesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tonalidades and returns the data updated in the database.
   * @param {TonalidadesUpdateManyAndReturnArgs} args - Arguments to update many Tonalidades.
   * @example
   * // Update many Tonalidades
   * const tonalidades = await prisma.tonalidades.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tonalidades and only return the `id`
   * const tonalidadesWithIdOnly = await prisma.tonalidades.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TonalidadesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TonalidadesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tonalidades.
   * @param {TonalidadesUpsertArgs} args - Arguments to update or create a Tonalidades.
   * @example
   * // Update or create a Tonalidades
   * const tonalidades = await prisma.tonalidades.upsert({
   *   create: {
   *     // ... data to create a Tonalidades
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tonalidades we want to update
   *   }
   * })
   */
  upsert<T extends TonalidadesUpsertArgs>(args: Prisma.SelectSubset<T, TonalidadesUpsertArgs<ExtArgs>>): Prisma.Prisma__TonalidadesClient<runtime.Types.Result.GetResult<Prisma.$TonalidadesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tonalidades.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TonalidadesCountArgs} args - Arguments to filter Tonalidades to count.
   * @example
   * // Count the number of Tonalidades
   * const count = await prisma.tonalidades.count({
   *   where: {
   *     // ... the filter for the Tonalidades we want to count
   *   }
   * })
  **/
  count<T extends TonalidadesCountArgs>(
    args?: Prisma.Subset<T, TonalidadesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TonalidadesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tonalidades.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TonalidadesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TonalidadesAggregateArgs>(args: Prisma.Subset<T, TonalidadesAggregateArgs>): Prisma.PrismaPromise<GetTonalidadesAggregateType<T>>

  /**
   * Group by Tonalidades.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TonalidadesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TonalidadesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TonalidadesGroupByArgs['orderBy'] }
      : { orderBy?: TonalidadesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TonalidadesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTonalidadesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Tonalidades model
 */
readonly fields: TonalidadesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Tonalidades.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TonalidadesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Musicas<T extends Prisma.Tonalidades$MusicasArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tonalidades$MusicasArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MusicasPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Tonalidades model
 */
export interface TonalidadesFieldRefs {
  readonly id: Prisma.FieldRef<"Tonalidades", 'String'>
  readonly tom: Prisma.FieldRef<"Tonalidades", 'String'>
  readonly created_at: Prisma.FieldRef<"Tonalidades", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Tonalidades", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Tonalidades findUnique
 */
export type TonalidadesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TonalidadesInclude<ExtArgs> | null
  /**
   * Filter, which Tonalidades to fetch.
   */
  where: Prisma.TonalidadesWhereUniqueInput
}

/**
 * Tonalidades findUniqueOrThrow
 */
export type TonalidadesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TonalidadesInclude<ExtArgs> | null
  /**
   * Filter, which Tonalidades to fetch.
   */
  where: Prisma.TonalidadesWhereUniqueInput
}

/**
 * Tonalidades findFirst
 */
export type TonalidadesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TonalidadesInclude<ExtArgs> | null
  /**
   * Filter, which Tonalidades to fetch.
   */
  where?: Prisma.TonalidadesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tonalidades to fetch.
   */
  orderBy?: Prisma.TonalidadesOrderByWithRelationInput | Prisma.TonalidadesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tonalidades.
   */
  cursor?: Prisma.TonalidadesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tonalidades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tonalidades.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tonalidades.
   */
  distinct?: Prisma.TonalidadesScalarFieldEnum | Prisma.TonalidadesScalarFieldEnum[]
}

/**
 * Tonalidades findFirstOrThrow
 */
export type TonalidadesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TonalidadesInclude<ExtArgs> | null
  /**
   * Filter, which Tonalidades to fetch.
   */
  where?: Prisma.TonalidadesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tonalidades to fetch.
   */
  orderBy?: Prisma.TonalidadesOrderByWithRelationInput | Prisma.TonalidadesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tonalidades.
   */
  cursor?: Prisma.TonalidadesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tonalidades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tonalidades.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tonalidades.
   */
  distinct?: Prisma.TonalidadesScalarFieldEnum | Prisma.TonalidadesScalarFieldEnum[]
}

/**
 * Tonalidades findMany
 */
export type TonalidadesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TonalidadesInclude<ExtArgs> | null
  /**
   * Filter, which Tonalidades to fetch.
   */
  where?: Prisma.TonalidadesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tonalidades to fetch.
   */
  orderBy?: Prisma.TonalidadesOrderByWithRelationInput | Prisma.TonalidadesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tonalidades.
   */
  cursor?: Prisma.TonalidadesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tonalidades from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tonalidades.
   */
  skip?: number
  distinct?: Prisma.TonalidadesScalarFieldEnum | Prisma.TonalidadesScalarFieldEnum[]
}

/**
 * Tonalidades create
 */
export type TonalidadesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TonalidadesInclude<ExtArgs> | null
  /**
   * The data needed to create a Tonalidades.
   */
  data: Prisma.XOR<Prisma.TonalidadesCreateInput, Prisma.TonalidadesUncheckedCreateInput>
}

/**
 * Tonalidades createMany
 */
export type TonalidadesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tonalidades.
   */
  data: Prisma.TonalidadesCreateManyInput | Prisma.TonalidadesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Tonalidades createManyAndReturn
 */
export type TonalidadesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * The data used to create many Tonalidades.
   */
  data: Prisma.TonalidadesCreateManyInput | Prisma.TonalidadesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Tonalidades update
 */
export type TonalidadesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TonalidadesInclude<ExtArgs> | null
  /**
   * The data needed to update a Tonalidades.
   */
  data: Prisma.XOR<Prisma.TonalidadesUpdateInput, Prisma.TonalidadesUncheckedUpdateInput>
  /**
   * Choose, which Tonalidades to update.
   */
  where: Prisma.TonalidadesWhereUniqueInput
}

/**
 * Tonalidades updateMany
 */
export type TonalidadesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tonalidades.
   */
  data: Prisma.XOR<Prisma.TonalidadesUpdateManyMutationInput, Prisma.TonalidadesUncheckedUpdateManyInput>
  /**
   * Filter which Tonalidades to update
   */
  where?: Prisma.TonalidadesWhereInput
  /**
   * Limit how many Tonalidades to update.
   */
  limit?: number
}

/**
 * Tonalidades updateManyAndReturn
 */
export type TonalidadesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * The data used to update Tonalidades.
   */
  data: Prisma.XOR<Prisma.TonalidadesUpdateManyMutationInput, Prisma.TonalidadesUncheckedUpdateManyInput>
  /**
   * Filter which Tonalidades to update
   */
  where?: Prisma.TonalidadesWhereInput
  /**
   * Limit how many Tonalidades to update.
   */
  limit?: number
}

/**
 * Tonalidades upsert
 */
export type TonalidadesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TonalidadesInclude<ExtArgs> | null
  /**
   * The filter to search for the Tonalidades to update in case it exists.
   */
  where: Prisma.TonalidadesWhereUniqueInput
  /**
   * In case the Tonalidades found by the `where` argument doesn't exist, create a new Tonalidades with this data.
   */
  create: Prisma.XOR<Prisma.TonalidadesCreateInput, Prisma.TonalidadesUncheckedCreateInput>
  /**
   * In case the Tonalidades was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TonalidadesUpdateInput, Prisma.TonalidadesUncheckedUpdateInput>
}

/**
 * Tonalidades delete
 */
export type TonalidadesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TonalidadesInclude<ExtArgs> | null
  /**
   * Filter which Tonalidades to delete.
   */
  where: Prisma.TonalidadesWhereUniqueInput
}

/**
 * Tonalidades deleteMany
 */
export type TonalidadesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tonalidades to delete
   */
  where?: Prisma.TonalidadesWhereInput
  /**
   * Limit how many Tonalidades to delete.
   */
  limit?: number
}

/**
 * Tonalidades.Musicas
 */
export type Tonalidades$MusicasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Musicas
   */
  select?: Prisma.MusicasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Musicas
   */
  omit?: Prisma.MusicasOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MusicasInclude<ExtArgs> | null
  where?: Prisma.MusicasWhereInput
  orderBy?: Prisma.MusicasOrderByWithRelationInput | Prisma.MusicasOrderByWithRelationInput[]
  cursor?: Prisma.MusicasWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MusicasScalarFieldEnum | Prisma.MusicasScalarFieldEnum[]
}

/**
 * Tonalidades without action
 */
export type TonalidadesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tonalidades
   */
  select?: Prisma.TonalidadesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tonalidades
   */
  omit?: Prisma.TonalidadesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TonalidadesInclude<ExtArgs> | null
}
