
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/library"
import type * as Prisma from "../models.ts"
import { type PrismaClient } from "./class.ts"

export type * from '../models.ts'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
 * Metrics
 */
export type Metrics = runtime.Metrics
export type Metric<T> = runtime.Metric<T>
export type MetricHistogram = runtime.MetricHistogram
export type MetricHistogramBucket = runtime.MetricHistogramBucket

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 6.18.0
 * Query Engine version: 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
 */
export const prismaVersion: PrismaVersion = {
  client: "6.18.0",
  engine: "34b5a692b7bd79939a9a2c3ef97d816e749cda2f"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Artistas: 'Artistas',
  Artistas_Musicas: 'Artistas_Musicas',
  Eventos: 'Eventos',
  Eventos_Musicas: 'Eventos_Musicas',
  Eventos_Integrantes: 'Eventos_Integrantes',
  Funcoes: 'Funcoes',
  Musicas: 'Musicas',
  Musicas_Funcoes: 'Musicas_Funcoes',
  Integrantes: 'Integrantes',
  Integrantes_Funcoes: 'Integrantes_Funcoes',
  Tipos_Eventos: 'Tipos_Eventos',
  Tonalidades: 'Tonalidades'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "artistas" | "artistas_Musicas" | "eventos" | "eventos_Musicas" | "eventos_Integrantes" | "funcoes" | "musicas" | "musicas_Funcoes" | "integrantes" | "integrantes_Funcoes" | "tipos_Eventos" | "tonalidades"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Artistas: {
      payload: Prisma.$ArtistasPayload<ExtArgs>
      fields: Prisma.ArtistasFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ArtistasFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArtistasPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ArtistasFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArtistasPayload>
        }
        findFirst: {
          args: Prisma.ArtistasFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArtistasPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ArtistasFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArtistasPayload>
        }
        findMany: {
          args: Prisma.ArtistasFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArtistasPayload>[]
        }
        create: {
          args: Prisma.ArtistasCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArtistasPayload>
        }
        createMany: {
          args: Prisma.ArtistasCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ArtistasCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArtistasPayload>[]
        }
        delete: {
          args: Prisma.ArtistasDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArtistasPayload>
        }
        update: {
          args: Prisma.ArtistasUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArtistasPayload>
        }
        deleteMany: {
          args: Prisma.ArtistasDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ArtistasUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ArtistasUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArtistasPayload>[]
        }
        upsert: {
          args: Prisma.ArtistasUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArtistasPayload>
        }
        aggregate: {
          args: Prisma.ArtistasAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateArtistas>
        }
        groupBy: {
          args: Prisma.ArtistasGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ArtistasGroupByOutputType>[]
        }
        count: {
          args: Prisma.ArtistasCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ArtistasCountAggregateOutputType> | number
        }
      }
    }
    Artistas_Musicas: {
      payload: Prisma.$Artistas_MusicasPayload<ExtArgs>
      fields: Prisma.Artistas_MusicasFieldRefs
      operations: {
        findUnique: {
          args: Prisma.Artistas_MusicasFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Artistas_MusicasPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.Artistas_MusicasFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Artistas_MusicasPayload>
        }
        findFirst: {
          args: Prisma.Artistas_MusicasFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Artistas_MusicasPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.Artistas_MusicasFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Artistas_MusicasPayload>
        }
        findMany: {
          args: Prisma.Artistas_MusicasFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Artistas_MusicasPayload>[]
        }
        create: {
          args: Prisma.Artistas_MusicasCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Artistas_MusicasPayload>
        }
        createMany: {
          args: Prisma.Artistas_MusicasCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.Artistas_MusicasCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Artistas_MusicasPayload>[]
        }
        delete: {
          args: Prisma.Artistas_MusicasDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Artistas_MusicasPayload>
        }
        update: {
          args: Prisma.Artistas_MusicasUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Artistas_MusicasPayload>
        }
        deleteMany: {
          args: Prisma.Artistas_MusicasDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.Artistas_MusicasUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.Artistas_MusicasUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Artistas_MusicasPayload>[]
        }
        upsert: {
          args: Prisma.Artistas_MusicasUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Artistas_MusicasPayload>
        }
        aggregate: {
          args: Prisma.Artistas_MusicasAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateArtistas_Musicas>
        }
        groupBy: {
          args: Prisma.Artistas_MusicasGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Artistas_MusicasGroupByOutputType>[]
        }
        count: {
          args: Prisma.Artistas_MusicasCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Artistas_MusicasCountAggregateOutputType> | number
        }
      }
    }
    Eventos: {
      payload: Prisma.$EventosPayload<ExtArgs>
      fields: Prisma.EventosFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EventosFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EventosPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EventosFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EventosPayload>
        }
        findFirst: {
          args: Prisma.EventosFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EventosPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EventosFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EventosPayload>
        }
        findMany: {
          args: Prisma.EventosFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EventosPayload>[]
        }
        create: {
          args: Prisma.EventosCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EventosPayload>
        }
        createMany: {
          args: Prisma.EventosCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.EventosCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EventosPayload>[]
        }
        delete: {
          args: Prisma.EventosDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EventosPayload>
        }
        update: {
          args: Prisma.EventosUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EventosPayload>
        }
        deleteMany: {
          args: Prisma.EventosDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EventosUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.EventosUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EventosPayload>[]
        }
        upsert: {
          args: Prisma.EventosUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EventosPayload>
        }
        aggregate: {
          args: Prisma.EventosAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEventos>
        }
        groupBy: {
          args: Prisma.EventosGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EventosGroupByOutputType>[]
        }
        count: {
          args: Prisma.EventosCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EventosCountAggregateOutputType> | number
        }
      }
    }
    Eventos_Musicas: {
      payload: Prisma.$Eventos_MusicasPayload<ExtArgs>
      fields: Prisma.Eventos_MusicasFieldRefs
      operations: {
        findUnique: {
          args: Prisma.Eventos_MusicasFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_MusicasPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.Eventos_MusicasFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_MusicasPayload>
        }
        findFirst: {
          args: Prisma.Eventos_MusicasFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_MusicasPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.Eventos_MusicasFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_MusicasPayload>
        }
        findMany: {
          args: Prisma.Eventos_MusicasFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_MusicasPayload>[]
        }
        create: {
          args: Prisma.Eventos_MusicasCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_MusicasPayload>
        }
        createMany: {
          args: Prisma.Eventos_MusicasCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.Eventos_MusicasCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_MusicasPayload>[]
        }
        delete: {
          args: Prisma.Eventos_MusicasDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_MusicasPayload>
        }
        update: {
          args: Prisma.Eventos_MusicasUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_MusicasPayload>
        }
        deleteMany: {
          args: Prisma.Eventos_MusicasDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.Eventos_MusicasUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.Eventos_MusicasUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_MusicasPayload>[]
        }
        upsert: {
          args: Prisma.Eventos_MusicasUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_MusicasPayload>
        }
        aggregate: {
          args: Prisma.Eventos_MusicasAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEventos_Musicas>
        }
        groupBy: {
          args: Prisma.Eventos_MusicasGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Eventos_MusicasGroupByOutputType>[]
        }
        count: {
          args: Prisma.Eventos_MusicasCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Eventos_MusicasCountAggregateOutputType> | number
        }
      }
    }
    Eventos_Integrantes: {
      payload: Prisma.$Eventos_IntegrantesPayload<ExtArgs>
      fields: Prisma.Eventos_IntegrantesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.Eventos_IntegrantesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_IntegrantesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.Eventos_IntegrantesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_IntegrantesPayload>
        }
        findFirst: {
          args: Prisma.Eventos_IntegrantesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_IntegrantesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.Eventos_IntegrantesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_IntegrantesPayload>
        }
        findMany: {
          args: Prisma.Eventos_IntegrantesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_IntegrantesPayload>[]
        }
        create: {
          args: Prisma.Eventos_IntegrantesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_IntegrantesPayload>
        }
        createMany: {
          args: Prisma.Eventos_IntegrantesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.Eventos_IntegrantesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_IntegrantesPayload>[]
        }
        delete: {
          args: Prisma.Eventos_IntegrantesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_IntegrantesPayload>
        }
        update: {
          args: Prisma.Eventos_IntegrantesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_IntegrantesPayload>
        }
        deleteMany: {
          args: Prisma.Eventos_IntegrantesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.Eventos_IntegrantesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.Eventos_IntegrantesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_IntegrantesPayload>[]
        }
        upsert: {
          args: Prisma.Eventos_IntegrantesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Eventos_IntegrantesPayload>
        }
        aggregate: {
          args: Prisma.Eventos_IntegrantesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEventos_Integrantes>
        }
        groupBy: {
          args: Prisma.Eventos_IntegrantesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Eventos_IntegrantesGroupByOutputType>[]
        }
        count: {
          args: Prisma.Eventos_IntegrantesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Eventos_IntegrantesCountAggregateOutputType> | number
        }
      }
    }
    Funcoes: {
      payload: Prisma.$FuncoesPayload<ExtArgs>
      fields: Prisma.FuncoesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FuncoesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FuncoesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FuncoesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FuncoesPayload>
        }
        findFirst: {
          args: Prisma.FuncoesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FuncoesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FuncoesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FuncoesPayload>
        }
        findMany: {
          args: Prisma.FuncoesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FuncoesPayload>[]
        }
        create: {
          args: Prisma.FuncoesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FuncoesPayload>
        }
        createMany: {
          args: Prisma.FuncoesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FuncoesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FuncoesPayload>[]
        }
        delete: {
          args: Prisma.FuncoesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FuncoesPayload>
        }
        update: {
          args: Prisma.FuncoesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FuncoesPayload>
        }
        deleteMany: {
          args: Prisma.FuncoesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FuncoesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FuncoesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FuncoesPayload>[]
        }
        upsert: {
          args: Prisma.FuncoesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FuncoesPayload>
        }
        aggregate: {
          args: Prisma.FuncoesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFuncoes>
        }
        groupBy: {
          args: Prisma.FuncoesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FuncoesGroupByOutputType>[]
        }
        count: {
          args: Prisma.FuncoesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FuncoesCountAggregateOutputType> | number
        }
      }
    }
    Musicas: {
      payload: Prisma.$MusicasPayload<ExtArgs>
      fields: Prisma.MusicasFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MusicasFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MusicasPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MusicasFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MusicasPayload>
        }
        findFirst: {
          args: Prisma.MusicasFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MusicasPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MusicasFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MusicasPayload>
        }
        findMany: {
          args: Prisma.MusicasFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MusicasPayload>[]
        }
        create: {
          args: Prisma.MusicasCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MusicasPayload>
        }
        createMany: {
          args: Prisma.MusicasCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MusicasCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MusicasPayload>[]
        }
        delete: {
          args: Prisma.MusicasDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MusicasPayload>
        }
        update: {
          args: Prisma.MusicasUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MusicasPayload>
        }
        deleteMany: {
          args: Prisma.MusicasDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MusicasUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MusicasUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MusicasPayload>[]
        }
        upsert: {
          args: Prisma.MusicasUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MusicasPayload>
        }
        aggregate: {
          args: Prisma.MusicasAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMusicas>
        }
        groupBy: {
          args: Prisma.MusicasGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MusicasGroupByOutputType>[]
        }
        count: {
          args: Prisma.MusicasCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MusicasCountAggregateOutputType> | number
        }
      }
    }
    Musicas_Funcoes: {
      payload: Prisma.$Musicas_FuncoesPayload<ExtArgs>
      fields: Prisma.Musicas_FuncoesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.Musicas_FuncoesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Musicas_FuncoesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.Musicas_FuncoesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Musicas_FuncoesPayload>
        }
        findFirst: {
          args: Prisma.Musicas_FuncoesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Musicas_FuncoesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.Musicas_FuncoesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Musicas_FuncoesPayload>
        }
        findMany: {
          args: Prisma.Musicas_FuncoesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Musicas_FuncoesPayload>[]
        }
        create: {
          args: Prisma.Musicas_FuncoesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Musicas_FuncoesPayload>
        }
        createMany: {
          args: Prisma.Musicas_FuncoesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.Musicas_FuncoesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Musicas_FuncoesPayload>[]
        }
        delete: {
          args: Prisma.Musicas_FuncoesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Musicas_FuncoesPayload>
        }
        update: {
          args: Prisma.Musicas_FuncoesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Musicas_FuncoesPayload>
        }
        deleteMany: {
          args: Prisma.Musicas_FuncoesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.Musicas_FuncoesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.Musicas_FuncoesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Musicas_FuncoesPayload>[]
        }
        upsert: {
          args: Prisma.Musicas_FuncoesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Musicas_FuncoesPayload>
        }
        aggregate: {
          args: Prisma.Musicas_FuncoesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMusicas_Funcoes>
        }
        groupBy: {
          args: Prisma.Musicas_FuncoesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Musicas_FuncoesGroupByOutputType>[]
        }
        count: {
          args: Prisma.Musicas_FuncoesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Musicas_FuncoesCountAggregateOutputType> | number
        }
      }
    }
    Integrantes: {
      payload: Prisma.$IntegrantesPayload<ExtArgs>
      fields: Prisma.IntegrantesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.IntegrantesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IntegrantesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.IntegrantesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IntegrantesPayload>
        }
        findFirst: {
          args: Prisma.IntegrantesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IntegrantesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.IntegrantesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IntegrantesPayload>
        }
        findMany: {
          args: Prisma.IntegrantesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IntegrantesPayload>[]
        }
        create: {
          args: Prisma.IntegrantesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IntegrantesPayload>
        }
        createMany: {
          args: Prisma.IntegrantesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.IntegrantesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IntegrantesPayload>[]
        }
        delete: {
          args: Prisma.IntegrantesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IntegrantesPayload>
        }
        update: {
          args: Prisma.IntegrantesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IntegrantesPayload>
        }
        deleteMany: {
          args: Prisma.IntegrantesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.IntegrantesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.IntegrantesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IntegrantesPayload>[]
        }
        upsert: {
          args: Prisma.IntegrantesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IntegrantesPayload>
        }
        aggregate: {
          args: Prisma.IntegrantesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateIntegrantes>
        }
        groupBy: {
          args: Prisma.IntegrantesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IntegrantesGroupByOutputType>[]
        }
        count: {
          args: Prisma.IntegrantesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IntegrantesCountAggregateOutputType> | number
        }
      }
    }
    Integrantes_Funcoes: {
      payload: Prisma.$Integrantes_FuncoesPayload<ExtArgs>
      fields: Prisma.Integrantes_FuncoesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.Integrantes_FuncoesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Integrantes_FuncoesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.Integrantes_FuncoesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Integrantes_FuncoesPayload>
        }
        findFirst: {
          args: Prisma.Integrantes_FuncoesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Integrantes_FuncoesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.Integrantes_FuncoesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Integrantes_FuncoesPayload>
        }
        findMany: {
          args: Prisma.Integrantes_FuncoesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Integrantes_FuncoesPayload>[]
        }
        create: {
          args: Prisma.Integrantes_FuncoesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Integrantes_FuncoesPayload>
        }
        createMany: {
          args: Prisma.Integrantes_FuncoesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.Integrantes_FuncoesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Integrantes_FuncoesPayload>[]
        }
        delete: {
          args: Prisma.Integrantes_FuncoesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Integrantes_FuncoesPayload>
        }
        update: {
          args: Prisma.Integrantes_FuncoesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Integrantes_FuncoesPayload>
        }
        deleteMany: {
          args: Prisma.Integrantes_FuncoesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.Integrantes_FuncoesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.Integrantes_FuncoesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Integrantes_FuncoesPayload>[]
        }
        upsert: {
          args: Prisma.Integrantes_FuncoesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Integrantes_FuncoesPayload>
        }
        aggregate: {
          args: Prisma.Integrantes_FuncoesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateIntegrantes_Funcoes>
        }
        groupBy: {
          args: Prisma.Integrantes_FuncoesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Integrantes_FuncoesGroupByOutputType>[]
        }
        count: {
          args: Prisma.Integrantes_FuncoesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Integrantes_FuncoesCountAggregateOutputType> | number
        }
      }
    }
    Tipos_Eventos: {
      payload: Prisma.$Tipos_EventosPayload<ExtArgs>
      fields: Prisma.Tipos_EventosFieldRefs
      operations: {
        findUnique: {
          args: Prisma.Tipos_EventosFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Tipos_EventosPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.Tipos_EventosFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Tipos_EventosPayload>
        }
        findFirst: {
          args: Prisma.Tipos_EventosFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Tipos_EventosPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.Tipos_EventosFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Tipos_EventosPayload>
        }
        findMany: {
          args: Prisma.Tipos_EventosFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Tipos_EventosPayload>[]
        }
        create: {
          args: Prisma.Tipos_EventosCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Tipos_EventosPayload>
        }
        createMany: {
          args: Prisma.Tipos_EventosCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.Tipos_EventosCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Tipos_EventosPayload>[]
        }
        delete: {
          args: Prisma.Tipos_EventosDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Tipos_EventosPayload>
        }
        update: {
          args: Prisma.Tipos_EventosUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Tipos_EventosPayload>
        }
        deleteMany: {
          args: Prisma.Tipos_EventosDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.Tipos_EventosUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.Tipos_EventosUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Tipos_EventosPayload>[]
        }
        upsert: {
          args: Prisma.Tipos_EventosUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$Tipos_EventosPayload>
        }
        aggregate: {
          args: Prisma.Tipos_EventosAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTipos_Eventos>
        }
        groupBy: {
          args: Prisma.Tipos_EventosGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Tipos_EventosGroupByOutputType>[]
        }
        count: {
          args: Prisma.Tipos_EventosCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Tipos_EventosCountAggregateOutputType> | number
        }
      }
    }
    Tonalidades: {
      payload: Prisma.$TonalidadesPayload<ExtArgs>
      fields: Prisma.TonalidadesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TonalidadesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TonalidadesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TonalidadesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TonalidadesPayload>
        }
        findFirst: {
          args: Prisma.TonalidadesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TonalidadesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TonalidadesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TonalidadesPayload>
        }
        findMany: {
          args: Prisma.TonalidadesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TonalidadesPayload>[]
        }
        create: {
          args: Prisma.TonalidadesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TonalidadesPayload>
        }
        createMany: {
          args: Prisma.TonalidadesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TonalidadesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TonalidadesPayload>[]
        }
        delete: {
          args: Prisma.TonalidadesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TonalidadesPayload>
        }
        update: {
          args: Prisma.TonalidadesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TonalidadesPayload>
        }
        deleteMany: {
          args: Prisma.TonalidadesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TonalidadesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TonalidadesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TonalidadesPayload>[]
        }
        upsert: {
          args: Prisma.TonalidadesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TonalidadesPayload>
        }
        aggregate: {
          args: Prisma.TonalidadesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTonalidades>
        }
        groupBy: {
          args: Prisma.TonalidadesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TonalidadesGroupByOutputType>[]
        }
        count: {
          args: Prisma.TonalidadesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TonalidadesCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ArtistasScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type ArtistasScalarFieldEnum = (typeof ArtistasScalarFieldEnum)[keyof typeof ArtistasScalarFieldEnum]


export const Artistas_MusicasScalarFieldEnum = {
  id: 'id',
  artista_id: 'artista_id',
  musica_id: 'musica_id',
  bpm: 'bpm',
  cifras: 'cifras',
  lyrics: 'lyrics',
  link_versao: 'link_versao',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Artistas_MusicasScalarFieldEnum = (typeof Artistas_MusicasScalarFieldEnum)[keyof typeof Artistas_MusicasScalarFieldEnum]


export const EventosScalarFieldEnum = {
  id: 'id',
  data: 'data',
  fk_tipo_evento: 'fk_tipo_evento',
  descricao: 'descricao',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type EventosScalarFieldEnum = (typeof EventosScalarFieldEnum)[keyof typeof EventosScalarFieldEnum]


export const Eventos_MusicasScalarFieldEnum = {
  id: 'id',
  evento_id: 'evento_id',
  musicas_id: 'musicas_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Eventos_MusicasScalarFieldEnum = (typeof Eventos_MusicasScalarFieldEnum)[keyof typeof Eventos_MusicasScalarFieldEnum]


export const Eventos_IntegrantesScalarFieldEnum = {
  id: 'id',
  evento_id: 'evento_id',
  musico_id: 'musico_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Eventos_IntegrantesScalarFieldEnum = (typeof Eventos_IntegrantesScalarFieldEnum)[keyof typeof Eventos_IntegrantesScalarFieldEnum]


export const FuncoesScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type FuncoesScalarFieldEnum = (typeof FuncoesScalarFieldEnum)[keyof typeof FuncoesScalarFieldEnum]


export const MusicasScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  fk_tonalidade: 'fk_tonalidade',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type MusicasScalarFieldEnum = (typeof MusicasScalarFieldEnum)[keyof typeof MusicasScalarFieldEnum]


export const Musicas_FuncoesScalarFieldEnum = {
  id: 'id',
  musica_id: 'musica_id',
  funcao_id: 'funcao_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Musicas_FuncoesScalarFieldEnum = (typeof Musicas_FuncoesScalarFieldEnum)[keyof typeof Musicas_FuncoesScalarFieldEnum]


export const IntegrantesScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  doc_id: 'doc_id',
  email: 'email',
  senha: 'senha',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type IntegrantesScalarFieldEnum = (typeof IntegrantesScalarFieldEnum)[keyof typeof IntegrantesScalarFieldEnum]


export const Integrantes_FuncoesScalarFieldEnum = {
  id: 'id',
  musico_id: 'musico_id',
  funcao_id: 'funcao_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Integrantes_FuncoesScalarFieldEnum = (typeof Integrantes_FuncoesScalarFieldEnum)[keyof typeof Integrantes_FuncoesScalarFieldEnum]


export const Tipos_EventosScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Tipos_EventosScalarFieldEnum = (typeof Tipos_EventosScalarFieldEnum)[keyof typeof Tipos_EventosScalarFieldEnum]


export const TonalidadesScalarFieldEnum = {
  id: 'id',
  tom: 'tom',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type TonalidadesScalarFieldEnum = (typeof TonalidadesScalarFieldEnum)[keyof typeof TonalidadesScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}


export type Datasource = {
  url?: string
}
export type Datasources = {
  db?: Datasource
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export interface PrismaClientOptions {
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasources?: Datasources
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasourceUrl?: string
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#the-log-option).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-planetscale`
   */
  adapter?: runtime.SqlDriverAdapterFactory | null
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
}
export type GlobalOmitConfig = {
  artistas?: Prisma.ArtistasOmit
  artistas_Musicas?: Prisma.Artistas_MusicasOmit
  eventos?: Prisma.EventosOmit
  eventos_Musicas?: Prisma.Eventos_MusicasOmit
  eventos_Integrantes?: Prisma.Eventos_IntegrantesOmit
  funcoes?: Prisma.FuncoesOmit
  musicas?: Prisma.MusicasOmit
  musicas_Funcoes?: Prisma.Musicas_FuncoesOmit
  integrantes?: Prisma.IntegrantesOmit
  integrantes_Funcoes?: Prisma.Integrantes_FuncoesOmit
  tipos_Eventos?: Prisma.Tipos_EventosOmit
  tonalidades?: Prisma.TonalidadesOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

